// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/Discover" | "/about" | "/about/mission" | "/about/story" | "/about/team" | "/accounts" | "/app-download" | "/approvals/[itemId]" | "/attendance" | "/auth" | "/auth/popup-success" | "/auth/verify" | "/bookcatering" | "/bookstall" | "/bookvenue" | "/catering" | "/cfo" | "/club/[id]" | "/clubeditor/[id]" | "/clubs" | "/contact" | "/cookies" | "/create/clubs" | "/create/event" | "/create/fest" | "/dean" | "/edit/clubs/[id]" | "/edit/event/[id]" | "/edit/fest/[id]" | "/error" | "/event/[id]" | "/event/[id]/participants" | "/event/[id]/register" | "/event/[id]/ticket/[registrationId]" | "/events" | "/faq" | "/feedback/[eventId]" | "/feedbacks/[eventId]" | "/fest/[id]" | "/fests" | "/guide/masteradmin" | "/guide/organiser" | "/hod" | "/it" | "/manage" | "/masteradmin" | "/pricing" | "/privacy" | "/profile" | "/refunds" | "/solutions" | "/stalls" | "/statuscheck" | "/support" | "/support/careers" | "/support/inbox" | "/terms" | "/venue" | "/volunteer" | "/volunteer/scanner/[eventId]"
type AppRouteHandlerRoutes = "/api/chat" | "/api/chatbot/fetch-content" | "/api/clubs/[clubId]/apply" | "/api/events" | "/api/events/[eventId]" | "/api/events/[eventId]/archive" | "/api/fests" | "/api/fests/[festId]" | "/api/fests/[festId]/archive" | "/auth/callback" | "/googlef9d3f1696ce89505.html"
type PageRoutes = never
type LayoutRoutes = "/" | "/Discover" | "/about" | "/about/mission" | "/about/story" | "/about/team" | "/app-download" | "/auth" | "/clubs" | "/contact" | "/cookies" | "/event/[id]" | "/events" | "/faq" | "/fests" | "/pricing" | "/privacy" | "/refunds" | "/solutions" | "/support" | "/terms"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/about/mission": {}
  "/about/story": {}
  "/about/team": {}
  "/accounts": {}
  "/api/chat": {}
  "/api/chatbot/fetch-content": {}
  "/api/clubs/[clubId]/apply": { "clubId": string; }
  "/api/events": {}
  "/api/events/[eventId]": { "eventId": string; }
  "/api/events/[eventId]/archive": { "eventId": string; }
  "/api/fests": {}
  "/api/fests/[festId]": { "festId": string; }
  "/api/fests/[festId]/archive": { "festId": string; }
  "/app-download": {}
  "/approvals/[itemId]": { "itemId": string; }
  "/attendance": {}
  "/auth": {}
  "/auth/callback": {}
  "/auth/popup-success": {}
  "/auth/verify": {}
  "/bookcatering": {}
  "/bookstall": {}
  "/bookvenue": {}
  "/catering": {}
  "/cfo": {}
  "/club/[id]": { "id": string; }
  "/clubeditor/[id]": { "id": string; }
  "/clubs": {}
  "/contact": {}
  "/cookies": {}
  "/create/clubs": {}
  "/create/event": {}
  "/create/fest": {}
  "/dean": {}
  "/Discover": {}
  "/edit/clubs/[id]": { "id": string; }
  "/edit/event/[id]": { "id": string; }
  "/edit/fest/[id]": { "id": string; }
  "/error": {}
  "/event/[id]": { "id": string; }
  "/event/[id]/participants": { "id": string; }
  "/event/[id]/register": { "id": string; }
  "/event/[id]/ticket/[registrationId]": { "id": string; "registrationId": string; }
  "/events": {}
  "/faq": {}
  "/feedback/[eventId]": { "eventId": string; }
  "/feedbacks/[eventId]": { "eventId": string; }
  "/fest/[id]": { "id": string; }
  "/fests": {}
  "/googlef9d3f1696ce89505.html": {}
  "/guide/masteradmin": {}
  "/guide/organiser": {}
  "/hod": {}
  "/it": {}
  "/manage": {}
  "/masteradmin": {}
  "/pricing": {}
  "/privacy": {}
  "/profile": {}
  "/refunds": {}
  "/solutions": {}
  "/stalls": {}
  "/statuscheck": {}
  "/support": {}
  "/support/careers": {}
  "/support/inbox": {}
  "/terms": {}
  "/venue": {}
  "/volunteer": {}
  "/volunteer/scanner/[eventId]": { "eventId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/about/mission": never
  "/about/story": never
  "/about/team": never
  "/app-download": never
  "/auth": never
  "/clubs": never
  "/contact": never
  "/cookies": never
  "/Discover": never
  "/event/[id]": never
  "/events": never
  "/faq": never
  "/fests": never
  "/pricing": never
  "/privacy": never
  "/refunds": never
  "/solutions": never
  "/support": never
  "/terms": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
