// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/Discover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Discover">> = Specific
  const handler = {} as typeof import("../../app/Discover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/mission">> = Specific
  const handler = {} as typeof import("../../app/about/mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/story/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/story">> = Specific
  const handler = {} as typeof import("../../app/about/story/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/team">> = Specific
  const handler = {} as typeof import("../../app/about/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts">> = Specific
  const handler = {} as typeof import("../../app/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app-download/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app-download">> = Specific
  const handler = {} as typeof import("../../app/app-download/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/approvals/[itemId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals/[itemId]">> = Specific
  const handler = {} as typeof import("../../app/approvals/[itemId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/attendance">> = Specific
  const handler = {} as typeof import("../../app/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/popup-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/popup-success">> = Specific
  const handler = {} as typeof import("../../app/auth/popup-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify">> = Specific
  const handler = {} as typeof import("../../app/auth/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookcatering/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookcatering">> = Specific
  const handler = {} as typeof import("../../app/bookcatering/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookstall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookstall">> = Specific
  const handler = {} as typeof import("../../app/bookstall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookvenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookvenue">> = Specific
  const handler = {} as typeof import("../../app/bookvenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/catering/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catering">> = Specific
  const handler = {} as typeof import("../../app/catering/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cfo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cfo">> = Specific
  const handler = {} as typeof import("../../app/cfo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/club/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/club/[id]">> = Specific
  const handler = {} as typeof import("../../app/club/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/clubeditor/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clubeditor/[id]">> = Specific
  const handler = {} as typeof import("../../app/clubeditor/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/clubs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clubs">> = Specific
  const handler = {} as typeof import("../../app/clubs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/clubs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create/clubs">> = Specific
  const handler = {} as typeof import("../../app/create/clubs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create/event">> = Specific
  const handler = {} as typeof import("../../app/create/event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/fest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create/fest">> = Specific
  const handler = {} as typeof import("../../app/create/fest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dean/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dean">> = Specific
  const handler = {} as typeof import("../../app/dean/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/edit/clubs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edit/clubs/[id]">> = Specific
  const handler = {} as typeof import("../../app/edit/clubs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/edit/event/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edit/event/[id]">> = Specific
  const handler = {} as typeof import("../../app/edit/event/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/edit/fest/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edit/fest/[id]">> = Specific
  const handler = {} as typeof import("../../app/edit/fest/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error">> = Specific
  const handler = {} as typeof import("../../app/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/event/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/[id]">> = Specific
  const handler = {} as typeof import("../../app/event/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/event/[id]/participants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/[id]/participants">> = Specific
  const handler = {} as typeof import("../../app/event/[id]/participants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/event/[id]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/[id]/register">> = Specific
  const handler = {} as typeof import("../../app/event/[id]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/event/[id]/ticket/[registrationId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event/[id]/ticket/[registrationId]">> = Specific
  const handler = {} as typeof import("../../app/event/[id]/ticket/[registrationId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feedback/[eventId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback/[eventId]">> = Specific
  const handler = {} as typeof import("../../app/feedback/[eventId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feedbacks/[eventId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedbacks/[eventId]">> = Specific
  const handler = {} as typeof import("../../app/feedbacks/[eventId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fest/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fest/[id]">> = Specific
  const handler = {} as typeof import("../../app/fest/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fests">> = Specific
  const handler = {} as typeof import("../../app/fests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guide/masteradmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/masteradmin">> = Specific
  const handler = {} as typeof import("../../app/guide/masteradmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guide/organiser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/organiser">> = Specific
  const handler = {} as typeof import("../../app/guide/organiser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hod">> = Specific
  const handler = {} as typeof import("../../app/hod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/it/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it">> = Specific
  const handler = {} as typeof import("../../app/it/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manage">> = Specific
  const handler = {} as typeof import("../../app/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/masteradmin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masteradmin">> = Specific
  const handler = {} as typeof import("../../app/masteradmin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refunds">> = Specific
  const handler = {} as typeof import("../../app/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/solutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../app/solutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stalls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stalls">> = Specific
  const handler = {} as typeof import("../../app/stalls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/statuscheck/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/statuscheck">> = Specific
  const handler = {} as typeof import("../../app/statuscheck/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/careers">> = Specific
  const handler = {} as typeof import("../../app/support/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support/inbox">> = Specific
  const handler = {} as typeof import("../../app/support/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venue">> = Specific
  const handler = {} as typeof import("../../app/venue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/volunteer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/volunteer">> = Specific
  const handler = {} as typeof import("../../app/volunteer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/volunteer/scanner/[eventId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/volunteer/scanner/[eventId]">> = Specific
  const handler = {} as typeof import("../../app/volunteer/scanner/[eventId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chatbot/fetch-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chatbot/fetch-content">> = Specific
  const handler = {} as typeof import("../../app/api/chatbot/fetch-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clubs/[clubId]/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clubs/[clubId]/apply">> = Specific
  const handler = {} as typeof import("../../app/api/clubs/[clubId]/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/[eventId]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[eventId]/archive">> = Specific
  const handler = {} as typeof import("../../app/api/events/[eventId]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/[eventId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/[eventId]">> = Specific
  const handler = {} as typeof import("../../app/api/events/[eventId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fests/[festId]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fests/[festId]/archive">> = Specific
  const handler = {} as typeof import("../../app/api/fests/[festId]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fests/[festId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fests/[festId]">> = Specific
  const handler = {} as typeof import("../../app/api/fests/[festId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fests">> = Specific
  const handler = {} as typeof import("../../app/api/fests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/googlef9d3f1696ce89505.html/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/googlef9d3f1696ce89505.html">> = Specific
  const handler = {} as typeof import("../../app/googlef9d3f1696ce89505.html/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/Discover/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/Discover">> = Specific
  const handler = {} as typeof import("../../app/Discover/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/mission/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/mission">> = Specific
  const handler = {} as typeof import("../../app/about/mission/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/story/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/story">> = Specific
  const handler = {} as typeof import("../../app/about/story/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/team/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about/team">> = Specific
  const handler = {} as typeof import("../../app/about/team/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app-download/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app-download">> = Specific
  const handler = {} as typeof import("../../app/app-download/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/clubs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/clubs">> = Specific
  const handler = {} as typeof import("../../app/clubs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cookies/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../app/cookies/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/event/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/event/[id]">> = Specific
  const handler = {} as typeof import("../../app/event/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/events/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/events">> = Specific
  const handler = {} as typeof import("../../app/events/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/faq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../app/faq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fests/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/fests">> = Specific
  const handler = {} as typeof import("../../app/fests/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/refunds/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/refunds">> = Specific
  const handler = {} as typeof import("../../app/refunds/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/solutions/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/solutions">> = Specific
  const handler = {} as typeof import("../../app/solutions/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/support">> = Specific
  const handler = {} as typeof import("../../app/support/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
