-- Master checkpoint migration
-- Generated by combining prior migration files in order.
-- Checkpoint date: 2026-04-21

-- ===== BEGIN 001_add_fest_allow_outsiders.sql =====
-- Migration: Add allow_outsiders column to fest table
-- This enables fests to allow non-Christ University members to register

ALTER TABLE public.fest
ADD COLUMN IF NOT EXISTS allow_outsiders boolean DEFAULT false;

COMMENT ON COLUMN public.fest.allow_outsiders IS 'Whether this fest allows outsider (non-Christ University) registrations. When true, events under this fest inherit outsider access without individual CSO approval.';
-- ===== END 001_add_fest_allow_outsiders.sql =====

-- ===== BEGIN 002_new_supabase_schema_adv01_adv03.sql =====
-- SOCIO new Supabase schema (ADV-01 + ADV-02 + ADV-03 ready)
-- Date: 2026-03-30
--
-- Includes:
-- ADV-01: Stable event -> fest mapping via events.fest_id (ID-safe, title-change safe)
-- ADV-02: Canonical fest table name: public.fests
-- ADV-03: Indexes for heavy admin lists (page/search/sort friendly)
--
-- Run this in Supabase SQL Editor on the NEW project.

-- ------------------------------------------------------------
-- Extensions
-- ------------------------------------------------------------
create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Canonicalize legacy table name if needed (fest -> fests)
-- ------------------------------------------------------------
do $$
begin
  if to_regclass('public.fest') is not null and to_regclass('public.fests') is null then
    alter table public.fest rename to fests;
  end if;
end $$;

-- ------------------------------------------------------------
-- Core Tables
-- ------------------------------------------------------------

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  auth_uuid uuid unique,
  email text unique not null,
  name text,
  avatar_url text,

  is_organiser boolean not null default false,
  organiser_expires_at timestamptz,
  is_support boolean not null default false,
  support_expires_at timestamptz,
  is_masteradmin boolean not null default false,
  masteradmin_expires_at timestamptz,

  course text,
  register_number text,

  organization_type text not null default 'christ_member' check (organization_type in ('christ_member', 'outsider')),
  visitor_id text,
  outsider_name_edit_used boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_users_visitor_id on public.users(visitor_id) where visitor_id is not null;

create table if not exists public.fests (
  id uuid primary key default gen_random_uuid(),
  auth_uuid text,

  fest_id text unique not null,
  fest_title text not null,

  description text,
  opening_date date,
  closing_date date,
  fest_image_url text,
  venue text,
  status text,
  registration_deadline timestamptz,

  organizing_dept text,
  department_access jsonb not null default '[]'::jsonb,
  category text,

  contact_email text,
  contact_phone text,
  event_heads jsonb not null default '[]'::jsonb,
  custom_fields jsonb not null default '[]'::jsonb,

  timeline jsonb not null default '[]'::jsonb,
  sponsors jsonb not null default '[]'::jsonb,
  social_links jsonb not null default '[]'::jsonb,
  faqs jsonb not null default '[]'::jsonb,

  campus_hosted_at text,
  allowed_campuses jsonb not null default '[]'::jsonb,
  allow_outsiders boolean not null default false,

  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  auth_uuid text,

  event_id text unique not null,
  title text not null,
  description text,

  event_date date,
  end_date date,
  event_time time,
  venue text,

  category text,
  department_access jsonb not null default '[]'::jsonb,
  organizing_dept text,

  claims_applicable boolean not null default false,
  registration_fee numeric,
  outsider_registration_fee numeric,
  participants_per_team integer,
  max_participants integer,
  outsider_max_participants integer,
  total_participants integer not null default 0,

  event_image_url text,
  banner_url text,
  pdf_url text,

  rules jsonb not null default '[]'::jsonb,
  schedule jsonb not null default '[]'::jsonb,
  prizes jsonb not null default '[]'::jsonb,
  custom_fields jsonb not null default '[]'::jsonb,

  organizer_email text,
  organizer_phone text,
  whatsapp_invite_link text,

  registration_deadline timestamptz,
  allow_outsiders boolean not null default false,

  -- ADV-01 canonical relation (stable, ID-safe)
  fest_id text,

  -- Legacy compatibility field used by existing code paths.
  -- Kept in sync with fest_id by trigger below.
  fest text,

  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fk_events_fest_id
    foreign key (fest_id)
    references public.fests(fest_id)
    on update cascade
    on delete set null
);

create table if not exists public.registrations (
  id uuid primary key default gen_random_uuid(),
  registration_id text unique not null,
  event_id text,

  user_email text,
  register_id text,

  registration_type text check (registration_type in ('individual', 'team')),

  individual_name text,
  individual_email text,
  individual_register_number text,

  team_name text,
  team_leader_name text,
  team_leader_email text,
  team_leader_register_number text,
  teammates jsonb not null default '[]'::jsonb,

  participant_organization text not null default 'christ_member' check (participant_organization in ('christ_member', 'outsider')),

  qr_code_data jsonb,
  qr_code_generated_at timestamptz,

  created_at timestamptz not null default now(),

  constraint fk_registrations_event_id
    foreign key (event_id)
    references public.events(event_id)
    on update cascade
    on delete cascade
);

create table if not exists public.attendance_status (
  id uuid primary key default gen_random_uuid(),
  registration_id text unique not null,
  event_id text,
  status text check (status in ('attended', 'absent', 'pending')),
  marked_at timestamptz not null default now(),
  marked_by text
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_email text,
  title text not null,
  message text,
  type text,
  read boolean not null default false,

  event_id text,
  event_title text,
  action_url text,

  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  source text default 'contact',
  status text default 'new',
  handled_by uuid,
  handled_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.qr_scan_logs (
  id uuid primary key default gen_random_uuid(),
  registration_id text,
  event_id text,
  scanned_by text,
  scan_timestamp timestamptz not null default now(),
  scan_result text,
  scanner_info jsonb
);

-- ------------------------------------------------------------
-- ADV-01 migration helpers: keep events.fest and events.fest_id aligned
-- ------------------------------------------------------------

create or replace function public.sync_event_fest_fields()
returns trigger
language plpgsql
as $$
begin
  if new.fest_id is null and new.fest is not null then
    -- If legacy payload sends fest_id in fest text, accept it.
    new.fest_id := new.fest;
  elsif new.fest is null and new.fest_id is not null then
    -- Keep legacy field readable for old code.
    new.fest := new.fest_id;
  elsif new.fest_id is not null and new.fest is not null and new.fest <> new.fest_id then
    -- Canonical source is fest_id.
    new.fest := new.fest_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sync_event_fest_fields on public.events;
create trigger trg_sync_event_fest_fields
before insert or update on public.events
for each row execute function public.sync_event_fest_fields();

-- Backfill existing rows if any.
update public.events e
set fest_id = e.fest
where e.fest_id is null
  and e.fest is not null
  and exists (select 1 from public.fests f where f.fest_id = e.fest);

update public.events e
set fest_id = f.fest_id
from public.fests f
where e.fest_id is null
  and e.fest = f.fest_title;

update public.events
set fest = fest_id
where fest_id is not null
  and (fest is null or fest <> fest_id);

-- ------------------------------------------------------------
-- Auto-updated timestamps
-- ------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_fests_updated_at on public.fests;
create trigger trg_fests_updated_at
before update on public.fests
for each row execute function public.set_updated_at();

drop trigger if exists trg_events_updated_at on public.events;
create trigger trg_events_updated_at
before update on public.events
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- ADV-03 indexes for heavy admin list pagination/filter/sort
-- ------------------------------------------------------------

-- Users list
create index if not exists idx_users_created_at on public.users(created_at desc);
create index if not exists idx_users_email_lower on public.users((lower(email)));
create index if not exists idx_users_name_lower on public.users((lower(name)));
create index if not exists idx_users_roles on public.users(is_organiser, is_support, is_masteradmin);

-- Events list
create index if not exists idx_events_created_at on public.events(created_at desc);
create index if not exists idx_events_event_date on public.events(event_date desc);
create index if not exists idx_events_title_lower on public.events((lower(title)));
create index if not exists idx_events_dept_lower on public.events((lower(organizing_dept)));
create index if not exists idx_events_fest_id on public.events(fest_id);

-- Fests list
create index if not exists idx_fests_created_at on public.fests(created_at desc);
create index if not exists idx_fests_opening_date on public.fests(opening_date desc);
create index if not exists idx_fests_title_lower on public.fests((lower(fest_title)));
create index if not exists idx_fests_dept_lower on public.fests((lower(organizing_dept)));

-- Registration and attendance
create index if not exists idx_registrations_event_id on public.registrations(event_id);
create index if not exists idx_registrations_user_email on public.registrations(user_email);
create index if not exists idx_attendance_event_id on public.attendance_status(event_id);
create index if not exists idx_attendance_registration_id on public.attendance_status(registration_id);

-- Notifications
create index if not exists idx_notifications_user_read_created on public.notifications(user_email, read, created_at desc);

-- ------------------------------------------------------------
-- RLS (wide-open baseline; tighten later if needed)
-- ------------------------------------------------------------

alter table public.users enable row level security;
alter table public.fests enable row level security;
alter table public.events enable row level security;
alter table public.registrations enable row level security;
alter table public.attendance_status enable row level security;
alter table public.notifications enable row level security;
alter table public.contact_messages enable row level security;
alter table public.qr_scan_logs enable row level security;

drop policy if exists "Allow all access to users" on public.users;
create policy "Allow all access to users" on public.users for all using (true) with check (true);

drop policy if exists "Allow all access to fests" on public.fests;
create policy "Allow all access to fests" on public.fests for all using (true) with check (true);

drop policy if exists "Allow all access to events" on public.events;
create policy "Allow all access to events" on public.events for all using (true) with check (true);

drop policy if exists "Allow all access to registrations" on public.registrations;
create policy "Allow all access to registrations" on public.registrations for all using (true) with check (true);

drop policy if exists "Allow all access to attendance_status" on public.attendance_status;
create policy "Allow all access to attendance_status" on public.attendance_status for all using (true) with check (true);

drop policy if exists "Allow all access to notifications" on public.notifications;
create policy "Allow all access to notifications" on public.notifications for all using (true) with check (true);

drop policy if exists "Allow all access to contact_messages" on public.contact_messages;
create policy "Allow all access to contact_messages" on public.contact_messages for all using (true) with check (true);

drop policy if exists "Allow all access to qr_scan_logs" on public.qr_scan_logs;
create policy "Allow all access to qr_scan_logs" on public.qr_scan_logs for all using (true) with check (true);
-- ===== END 002_new_supabase_schema_adv01_adv03.sql =====

-- ===== BEGIN 003_add_admin_analytics_rpc_v1.sql =====
-- Adds a master-admin guarded analytics RPC for client-side Data Explorer.
-- This is intentionally additive and does not modify existing app RLS policies.

create or replace function public.is_masteradmin_session()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid;
  v_email text;
  v_is_masteradmin boolean := false;
begin
  v_uid := auth.uid();

  if v_uid is null then
    return false;
  end if;

  begin
    v_email := lower(coalesce(auth.jwt() ->> 'email', ''));
  exception when others then
    v_email := '';
  end;

  select coalesce(u.is_masteradmin, false)
    into v_is_masteradmin
  from public.users u
  where u.auth_uuid = v_uid
     or (v_email <> '' and lower(u.email) = v_email)
  order by case when u.auth_uuid = v_uid then 0 else 1 end
  limit 1;

  return coalesce(v_is_masteradmin, false);
end;
$$;

revoke all on function public.is_masteradmin_session() from public;
grant execute on function public.is_masteradmin_session() to authenticated;

create or replace function public.get_admin_analytics_dataset_v1(
  p_max_users integer default 20000,
  p_max_events integer default 25000,
  p_max_fests integer default 10000,
  p_max_registrations integer default 80000,
  p_max_attendance integer default 80000
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_has_users_campus boolean := false;
  v_has_users_department boolean := false;
  v_has_events_event_type boolean := false;
  v_has_events_campus boolean := false;
  v_has_events_fest_id boolean := false;
  v_has_events_outsider_fee boolean := false;
  v_has_fests_campus boolean := false;

  v_fest_table text := null;

  v_limit_users integer := greatest(1, least(coalesce(p_max_users, 20000), 50000));
  v_limit_events integer := greatest(1, least(coalesce(p_max_events, 25000), 50000));
  v_limit_fests integer := greatest(1, least(coalesce(p_max_fests, 10000), 50000));
  v_limit_registrations integer := greatest(1, least(coalesce(p_max_registrations, 80000), 200000));
  v_limit_attendance integer := greatest(1, least(coalesce(p_max_attendance, 80000), 200000));

  v_users jsonb := '[]'::jsonb;
  v_events jsonb := '[]'::jsonb;
  v_fests jsonb := '[]'::jsonb;
  v_registrations jsonb := '[]'::jsonb;
  v_attendance jsonb := '[]'::jsonb;

  v_sql text;
begin
  if not public.is_masteradmin_session() then
    raise exception 'Forbidden: master admin privileges required';
  end if;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'campus'
  ) into v_has_users_campus;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'department'
  ) into v_has_users_department;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'events' and column_name = 'event_type'
  ) into v_has_events_event_type;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'events' and column_name = 'campus_hosted_at'
  ) into v_has_events_campus;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'events' and column_name = 'fest_id'
  ) into v_has_events_fest_id;

  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'events' and column_name = 'outsider_registration_fee'
  ) into v_has_events_outsider_fee;

  if to_regclass('public.fests') is not null then
    v_fest_table := 'public.fests';
  elsif to_regclass('public.fest') is not null then
    v_fest_table := 'public.fest';
  else
    v_fest_table := null;
  end if;

  if v_fest_table is not null then
    v_sql := format(
      'select exists (select 1 from information_schema.columns where table_schema = ''public'' and table_name = %L and column_name = ''campus_hosted_at'')',
      replace(v_fest_table, 'public.', '')
    );
    execute v_sql into v_has_fests_campus;
  end if;

  v_sql := format(
    'select coalesce(jsonb_agg(to_jsonb(u)), ''[]''::jsonb) from (
       select
         email,
         name,
         %s as campus,
         %s as department,
         course,
         organization_type,
         is_organiser,
         is_support,
         is_masteradmin,
         created_at
       from public.users
       order by id asc
       limit %s
     ) u',
    case when v_has_users_campus then 'campus' else 'null::text' end,
    case when v_has_users_department then 'department' else 'null::text' end,
    v_limit_users
  );
  execute v_sql into v_users;

  v_sql := format(
    'select coalesce(jsonb_agg(to_jsonb(e)), ''[]''::jsonb) from (
       select
         event_id,
         title,
         event_date,
         created_at,
         category,
         %s as event_type,
         organizing_dept,
         %s as campus_hosted_at,
         coalesce(registration_fee, 0) as registration_fee,
         %s as outsider_registration_fee,
         %s as fest_id,
         fest,
         created_by
       from public.events
       order by id asc
       limit %s
     ) e',
    case when v_has_events_event_type then 'event_type' else 'null::text' end,
    case when v_has_events_campus then 'campus_hosted_at' else 'null::text' end,
    case when v_has_events_outsider_fee then 'coalesce(outsider_registration_fee, 0)' else '0::numeric' end,
    case when v_has_events_fest_id then 'fest_id' else 'null::text' end,
    v_limit_events
  );
  execute v_sql into v_events;

  if v_fest_table is not null then
    v_sql := format(
      'select coalesce(jsonb_agg(to_jsonb(f)), ''[]''::jsonb) from (
         select
           fest_id,
           fest_title,
           organizing_dept,
           %s as campus_hosted_at,
           opening_date,
           closing_date
         from %s
         order by id asc
         limit %s
       ) f',
      case when v_has_fests_campus then 'campus_hosted_at' else 'null::text' end,
      v_fest_table,
      v_limit_fests
    );
    execute v_sql into v_fests;
  end if;

  if to_regclass('public.registrations') is not null then
    v_sql := format(
      'select coalesce(jsonb_agg(to_jsonb(r)), ''[]''::jsonb) from (
         select
           registration_id,
           event_id,
           registration_type,
           participant_organization,
           user_email,
           individual_email,
           team_leader_email,
           teammates,
           created_at
         from public.registrations
         order by id asc
         limit %s
       ) r',
      v_limit_registrations
    );
    execute v_sql into v_registrations;
  end if;

  if to_regclass('public.attendance_status') is not null then
    v_sql := format(
      'select coalesce(jsonb_agg(to_jsonb(a)), ''[]''::jsonb) from (
         select
           registration_id,
           event_id,
           status,
           marked_at
         from public.attendance_status
         order by id asc
         limit %s
       ) a',
      v_limit_attendance
    );
    execute v_sql into v_attendance;
  end if;

  return jsonb_build_object(
    'generatedAt', now(),
    'users', v_users,
    'events', v_events,
    'fests', v_fests,
    'registrations', v_registrations,
    'attendance', v_attendance
  );
end;
$$;

revoke all on function public.get_admin_analytics_dataset_v1(integer, integer, integer, integer, integer) from public;
grant execute on function public.get_admin_analytics_dataset_v1(integer, integer, integer, integer, integer) to authenticated;
-- ===== END 003_add_admin_analytics_rpc_v1.sql =====

-- ===== BEGIN 003_add_event_archive_fields.sql =====
-- Migration: Add archive tracking fields for events
-- Purpose: support manual archive/unarchive and archived views in management UI.

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS archived_by TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_events_is_archived ON public.events (is_archived);
CREATE INDEX IF NOT EXISTS idx_events_archived_at ON public.events (archived_at DESC);
-- ===== END 003_add_event_archive_fields.sql =====

-- ===== BEGIN 004_departments_courses_data.sql =====
-- Migration: 004_departments_courses_data.sql
-- Purpose: Add departments_courses table with course-to-class mappings
-- Date: 2026-04-02
-- 
-- This migration:
-- 1. Creates the departments_courses table to store department info with courses in JSON
-- 2. Populates it with pre-generated department/course/class seed data
-- 3. Adds a foreign key reference in the users table to link users.course to departments_courses

-- ===========================================================================
-- Create departments_courses table
-- ===========================================================================

create table if not exists public.departments_courses (
  id uuid primary key default gen_random_uuid(),
  department_name text unique not null,
  school text,
  
  -- JSON structure:
  -- {
  --   "Course Full Name": [
  --     {
  --       "class": "2BBA A",
  --       "term": 2,
  --       "room": "905",
  --       "block": "AUDI BLOCK"
  --     },
  --     ...
  --   ],
  --   ...
  -- }
  courses_json jsonb not null default '[]'::jsonb,
  
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Create index for department lookups
create index if not exists idx_departments_courses_name on public.departments_courses(lower(department_name));

-- ===========================================================================
-- Populate departments_courses with extracted Excel data
-- ===========================================================================

INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'BUSINESS AND MANAGEMENT  (BBA)', E'SCHOOL OF BUSINESS AND MANAGEMENT', '{"Bachelor of Business Administration (BBA) - Bangalore Central Campus": [{"class": "2BBA A", "term": 2}, {"class": "2BBA B", "term": 2}, {"class": "2BBA C", "term": 2}, {"class": "2BBA D", "term": 2}, {"class": "2BBA E", "term": 2}, {"class": "2BBA F", "term": 2}, {"class": "4BBAA", "term": 4}, {"class": "4BBAB", "term": 4}, {"class": "4BBAC", "term": 4}, {"class": "4BBAD", "term": 4}, {"class": "4BBAE", "term": 4}, {"class": "4BBAF", "term": 4}, {"class": "6BBAA", "term": 6}, {"class": "6BBAB", "term": 6}, {"class": "6BBAC", "term": 6}, {"class": "6BBAD", "term": 6}, {"class": "6BBAE", "term": 6}, {"class": "6BBAF", "term": 6}], "BBA (Decision Science) - Bangalore Central Campus": [{"class": "2BBADS", "term": 2}, {"class": "4BBADS", "term": 4}, {"class": "6BBADS", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'BUSINESS AND MANAGEMENT  (MBA)', E'SCHOOL OF BUSINESS AND MANAGEMENT', '{"MBA Bangalore Central Campus": [{"class": "2MBAG", "term": 2}, {"class": "2MBAH", "term": 2}, {"class": "2MBAI", "term": 2}, {"class": "2MBAJ", "term": 2}, {"class": "2MBAK", "term": 2}, {"class": "2MBAL", "term": 2}, {"class": "2MBAM", "term": 2}, {"class": "2MBAN", "term": 2}, {"class": "4MBA MAIN BA2", "term": 4}, {"class": "4MBA MAIN BA3", "term": 4}, {"class": "4MBA MAIN F4", "term": 4}, {"class": "4MBA MAIN F5", "term": 4}, {"class": "4MBA MAIN F6", "term": 4}, {"class": "4MBA MAIN F7", "term": 4}, {"class": "4MBA MAIN F8", "term": 4}, {"class": "4MBA MAIN HR", "term": 4}, {"class": "4MBA MAIN LOS3", "term": 4}, {"class": "4MBA MAIN LOS4", "term": 4}, {"class": "4MBA MAIN M4", "term": 4}, {"class": "4MBA MAIN M5", "term": 4}, {"class": "4MBA MAIN M6", "term": 4}, {"class": "4MBA MAIN M7", "term": 4}, {"class": "6MBA MAIN BA2", "term": 6}, {"class": "6MBA MAIN BA3", "term": 6}, {"class": "6MBA MAIN F4", "term": 6}, {"class": "6MBA MAIN F5", "term": 6}, {"class": "6MBA MAIN F6", "term": 6}, {"class": "6MBA MAIN F7", "term": 6}, {"class": "6MBA MAIN F8", "term": 6}, {"class": "6MBA MAIN HR", "term": 6}, {"class": "6MBA MAIN LOS3", "term": 6}, {"class": "6MBA MAIN LOS4", "term": 6}, {"class": "6MBA MAIN M4", "term": 6}, {"class": "6MBA MAIN M5", "term": 6}, {"class": "6MBA MAIN M6", "term": 6}, {"class": "6MBA MAIN M7", "term": 6}], "MBA with German MBA": [{"class": "2MBAT", "term": 2}, {"class": "4MBAT", "term": 4}], "MBA with MS Business (VCU, USA)": [{"class": "2MBAV", "term": 2}, {"class": "4MBAV", "term": 4}], "MBA (Christ University) with MBA (Western Michigan University USA)": [{"class": "2MBAW", "term": 2}, {"class": "4MBAW", "term": 4}], "MBA Executive": [{"class": "2MBAX", "term": 2}, {"class": "4MBAX", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'CHEMISTRY', E'SCHOOL OF SCIENCES', '{"BSc (Chemistry, Zoology) - Bangalore Central Campus": [{"class": "2BScCZ", "term": 2}, {"class": "4BScCZ", "term": 4}, {"class": "6BScCZ", "term": 6}], "MSc Chemistry": [{"class": "2MCHE", "term": 2}, {"class": "4MCHE", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'COMMERCE', E'SCHOOL OF COMMERCE FINANCE AND ACCOUNTANCY', '{"Bachelor of Commerce (BCom) - Bangalore Central Campus": [{"class": "2BCOM A", "term": 2}, {"class": "2BCOM B", "term": 2}, {"class": "2BCOM C", "term": 2}, {"class": "2BCOM D", "term": 2}, {"class": "4BCOMA", "term": 4}, {"class": "4BCOMB", "term": 4}, {"class": "4BCOMC", "term": 4}, {"class": "4BCOMD", "term": 4}, {"class": "6BCOMA", "term": 6}, {"class": "6BCOMB", "term": 6}, {"class": "6BCOMC", "term": 6}, {"class": "6BCOMD", "term": 6}], "BCom (Morning) - Bangalore Central Campus": [{"class": "2BCOM F", "term": 2}, {"class": "4BCOMF", "term": 4}, {"class": "6BCOMF", "term": 6}], "BCom (Accountancy and Taxation) - Bangalore Central Campus": [{"class": "2BCOMA&T", "term": 2}, {"class": "4BCOMA&T", "term": 4}, {"class": "6BCOMA&T", "term": 6}], "BCom (Applied Finance and Analytics) - Bangalore Central Campus": [{"class": "2BCOMAFA", "term": 2}, {"class": "4BCOMAFA", "term": 4}, {"class": "6BCOMAFA", "term": 6}], "BCom (Finance and Investment) - Bangalore Central Campus": [{"class": "2BCOMF&I A", "term": 2}, {"class": "2BCOMF&I B", "term": 2}, {"class": "4BCOMF&I A", "term": 4}, {"class": "4BCOMF&I B", "term": 4}, {"class": "6BCOMF&I A", "term": 6}, {"class": "6BCOMF&I B", "term": 6}], "BCom (Strategic Finance) - Bangalore Central Campus": [{"class": "2BCOMSF", "term": 2}, {"class": "4BCOMSF", "term": 4}, {"class": "6BCOMSF", "term": 6}], "BSc (Accountancy and Analytics) - Bangalore Central Campus": [{"class": "2BSc A&A", "term": 2}, {"class": "4BSc A&A", "term": 4}], "Master of Commerce": [{"class": "2MCOM", "term": 2}, {"class": "4MCOM", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'COMPUTER SCIENCE', E'SCHOOL OF SCIENCES', '{"Bachelor of Computer Applications (BCA) - Bangalore Central Campus": [{"class": "2BCA A", "term": 2}, {"class": "2BCA B", "term": 2}, {"class": "4BCA A", "term": 4}, {"class": "4BCA B", "term": 4}, {"class": "6BCA A", "term": 6}, {"class": "6BCA B", "term": 6}], "BSc (Computer Science, Mathematics) - Bangalore Central Campus": [{"class": "2BScCM", "term": 2}, {"class": "4BScCM", "term": 4}, {"class": "6BScCM", "term": 6}], "BSc (Computer Science, Statistics) - Bangalore Central Campus": [{"class": "2BScCS", "term": 2}, {"class": "4BScCS", "term": 4}, {"class": "6BScCS", "term": 6}], "Master of Computer Applications": [{"class": "2MCA A", "term": 2}, {"class": "2MCA B", "term": 2}, {"class": "4MCA A", "term": 4}, {"class": "4MCA B", "term": 4}, {"class": "6MCA A", "term": 6}, {"class": "6MCA B", "term": 6}], "Master of Science (Artificial Intelligence and Machine Learning)": [{"class": "2MSAIM", "term": 2}, {"class": "4MSAIM", "term": 4}, {"class": "6MSAIM", "term": 6}], "MSc (Computer Science and Applications)": [{"class": "2MSCSA", "term": 2}, {"class": "4MSCSA", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'ECONOMICS', E'SCHOOL OF SOCIAL SCIENCES', '{"MA Applied Economics": [{"class": "2MAECO", "term": 2}, {"class": "4MAECO", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'ENGLISH AND CULTURAL STUDIES', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"MA in English with Communication Studies": [{"class": "2MENG", "term": 2}, {"class": "4MENG", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'HOTEL MANAGEMENT', E'SCHOOL OF BUSINESS AND MANAGEMENT', '{"Bachelor of Hotel Management": [{"class": "2BHM", "term": 2}, {"class": "4BHM", "term": 4}, {"class": "6BHM", "term": 6}, {"class": "8BHM", "term": 8}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'INTERNATIONAL STUDIES, POLITICAL SCIENCE AND HISTORY', E'SCHOOL OF SOCIAL SCIENCES', '{"BA (History, Political Science) - Bangalore Central Campus": [{"class": "2BAHP", "term": 2}, {"class": "4BAHP", "term": 4}, {"class": "6BAHP", "term": 6}], "Master of Arts  in  International Studies": [{"class": "2MAIS", "term": 2}, {"class": "4MAIS", "term": 4}], "MA (Public Policy)": [{"class": "2MAPP", "term": 2}, {"class": "4MAPP", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'LIFE SCIENCES', E'SCHOOL OF SCIENCES', '{"BSc (Biotechnology, Botany) - Bangalore Central Campus": [{"class": "2BScBtB", "term": 2}, {"class": "4BScBtB", "term": 4}, {"class": "6BScBtB", "term": 6}], "BSc (Biotechnology, Chemistry) - Bangalore Central Campus": [{"class": "2BScBtC", "term": 2}, {"class": "4BScBtC", "term": 4}, {"class": "6BScBtC", "term": 6}], "BSc (Biotechnology, Forensic Science) - Bangalore Central Campus": [{"class": "2BScBtF", "term": 2}, {"class": "4BScBtF", "term": 4}, {"class": "6BScBtF", "term": 6}], "BSc (Biotechnology, Zoology) - Bangalore Central Campus": [{"class": "2BScBtZ", "term": 2}, {"class": "4BScBtZ", "term": 4}, {"class": "6BScBtZ", "term": 6}], "BSc (Life Sciences) - Bangalore Central Campus": [{"class": "2BScLIF", "term": 2}, {"class": "4BScLIF", "term": 4}, {"class": "6BScLIF", "term": 6}], "Master of Science in Botany": [{"class": "2MBOT", "term": 2}, {"class": "4MBOT", "term": 4}], "Master of Science in Biotechnology": [{"class": "2MBTY", "term": 2}, {"class": "4MBTY", "term": 4}], "MSc (Forensic Science)": [{"class": "2MFS", "term": 2}, {"class": "4MFS", "term": 4}], "Master of Science in Zoology": [{"class": "2MZOO", "term": 2}, {"class": "4MZOO", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'MATHEMATICS', E'SCHOOL OF SCIENCES', '{"BSc (Economics, Mathematics, Statistics) - Bangalore Central Campus": [{"class": "2EMS", "term": 2}, {"class": "4EMS", "term": 4}, {"class": "6EMS", "term": 6}], "MSc Mathematics": [{"class": "2MMAT", "term": 2}, {"class": "4MMAT", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'MEDIA STUDIES', E'SCHOOL OF SOCIAL SCIENCES', '{"BA (Communication and Media, English) - Bangalore Central Campus": [{"class": "2BACE", "term": 2}, {"class": "4BACE", "term": 4}, {"class": "6BACE", "term": 6}], "BA (Communication and Media, Psychology) - Bangalore Central Campus": [{"class": "2BACP", "term": 2}, {"class": "4BACP", "term": 4}, {"class": "6BACP", "term": 6}], "BA (Journalism and Digital Media, English) - Bangalore Central Campus": [{"class": "2BAJE", "term": 2}, {"class": "4BAJE", "term": 4}, {"class": "6BAJE", "term": 6}], "MA (Media and Communication Studies)": [{"class": "2MAMCS ACC", "term": 2}, {"class": "2MAMCS DTCS", "term": 2}, {"class": "4MAMCS ACC", "term": 4}, {"class": "4MAMCS MJ", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'MUSIC', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"BA (Music-Western Classical, Creative Media) - Bangalore Central Campus": [{"class": "2BAMC", "term": 2}, {"class": "4BAMC", "term": 4}, {"class": "6BAMC", "term": 6}], "BA (Music-Western Classical, Psychology) - Bangalore Central Campus": [{"class": "2BAMP", "term": 2}, {"class": "4BAMP", "term": 4}, {"class": "6BAMP", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PERFORMING ARTS', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"BA (Performing Arts, Creative Media) - Bangalore Central Campus": [{"class": "2BAPC", "term": 2}, {"class": "4BAPC", "term": 4}, {"class": "6BAPC", "term": 6}], "BA (Performing Arts, Psychology) - Bangalore Central Campus": [{"class": "2BAPP", "term": 2}, {"class": "4BAPP", "term": 4}, {"class": "6BAPP", "term": 6}], "MA (Performing Arts - Bharatanatyam)": [{"class": "2MPAB", "term": 2}, {"class": "4MPAB", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PHILOSOPHY AND THEOLOGY', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"Bachelor of Arts in Philosophy": [{"class": "2BPHL", "term": 2}, {"class": "4BPHL", "term": 4}, {"class": "6BPHL", "term": 6}], "MA Counselling and Spirituality": [{"class": "2MACS", "term": 2}, {"class": "4MACS", "term": 4}], "MA (Religion)": [{"class": "2MARL A", "term": 2}, {"class": "4MARL A", "term": 4}], "MA Philosophy": [{"class": "2MPHL", "term": 2}, {"class": "4MPHL", "term": 4}], "PG Diploma (Religion)": [{"class": "2PGDR A", "term": 2}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PHYSICS AND ELECTRONICS', E'SCHOOL OF SCIENCES', '{"BSc (Physics, Chemistry/Honours/Honours with Research) with minor in Mathematics": [{"class": "2BScPCm", "term": 2}], "BSc (Physics, Mathematics/Honours/Honours with Research) with minor in Astrophysics": [{"class": "2BScPMa", "term": 2}], "MSc Physics": [{"class": "2MPHY", "term": 2}, {"class": "4MPHY", "term": 4}], "BSc (Physics, Chemistry) - Bangalore Central Campus": [{"class": "4BScPC", "term": 4}, {"class": "6BScPC", "term": 6}], "BSc (Physics, Mathematics) - Bangalore Central Campus": [{"class": "4BScPM", "term": 4}, {"class": "6BScPM", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PROFESSIONAL STUDIES', E'SCHOOL OF COMMERCE FINANCE AND ACCOUNTANCY', '{"BCom (Branding and Entrepreneurship) - Bangalore Central Campus": [{"class": "2BCOM B&E", "term": 2}], "BCom (Finance and Accountancy) - Bangalore Central Campus": [{"class": "2BCOMF&A A", "term": 2}, {"class": "2BCOMF&A B", "term": 2}, {"class": "2BCOMF&A C", "term": 2}, {"class": "2BCOMF&A D", "term": 2}, {"class": "4BCOMF&A A", "term": 4}, {"class": "4BCOMF&A B", "term": 4}, {"class": "4BCOMF&A C", "term": 4}, {"class": "4BCOMF&A D", "term": 4}, {"class": "6BCOMF&A A", "term": 6}, {"class": "6BCOMF&A B", "term": 6}, {"class": "6BCOMF&A C", "term": 6}, {"class": "6BCOMF&A D", "term": 6}], "BCom (International Accountancy and Finance) - Bangalore Central Campus": [{"class": "2BCOMIAF A", "term": 2}, {"class": "2BCOMIAF B", "term": 2}, {"class": "2BCOMIAF C", "term": 2}, {"class": "4BCOMIAF A", "term": 4}, {"class": "4BCOMIAF B", "term": 4}, {"class": "4BCOMIAF C", "term": 4}, {"class": "6BCOMIAF A", "term": 6}, {"class": "6BCOMIAF B", "term": 6}], "BCom (International Finance) - Bangalore Central Campus": [{"class": "2BCOMIF A", "term": 2}, {"class": "2BCOMIF B", "term": 2}, {"class": "4BCOMIF A", "term": 4}, {"class": "4BCOMIF B", "term": 4}, {"class": "6BCOMIF", "term": 6}], "BCom (Professional) - Bangalore Central Campus": [{"class": "2BCOMP A", "term": 2}, {"class": "4BCOMP A", "term": 4}, {"class": "4BCOMP B", "term": 4}, {"class": "6BCOMP A", "term": 6}, {"class": "6BCOMP B", "term": 6}], "BSc (Actuarial Science) - Bangalore Central Campus": [{"class": "2BScAS", "term": 2}], "MCom (International Finance)": [{"class": "2MCOM IF", "term": 2}, {"class": "4MCOM IF", "term": 4}], "MSc Actuarial Science": [{"class": "2MSAS", "term": 2}, {"class": "4MSAS", "term": 4}], "MSc (Innovation and Entrepreneurship)": [{"class": "2MSIE", "term": 2}, {"class": "4MSIE", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'PSYCHOLOGY', E'SCHOOL OF PSYCHOLOGICAL SCIENCES, EDUCATION AND SOCIAL WORK', '{"BA (Psychology, Economics) - Bangalore Central Campus": [{"class": "2BAPECO", "term": 2}, {"class": "4BAPECO", "term": 4}, {"class": "6BAPECO", "term": 6}], "BA (Psychology, English) - Bangalore Central Campus": [{"class": "2BAPENG", "term": 2}, {"class": "4BAPENG", "term": 4}, {"class": "6BAPENG", "term": 6}], "Master of Science in Psychology (Clinical)": [{"class": "2MPCL A", "term": 2}, {"class": "2MPCL B", "term": 2}, {"class": "4MPCL A", "term": 4}, {"class": "4MPCL B", "term": 4}], "Master of Science in Psychology (Counselling)": [{"class": "2MPCO", "term": 2}, {"class": "4MPCO", "term": 4}], "MSc (Clinical Psycho-Oncology)": [{"class": "2MPCPO", "term": 2}, {"class": "4MPCPO", "term": 4}], "Master of Science in Psychology (HRDM)": [{"class": "2MPHR", "term": 2}, {"class": "4MPHR", "term": 4}], "MSc (Psychology-HRDM) with MA (Business and Organisational Psychology) [Steinbeis, Germany]": [{"class": "2MPHRG", "term": 2}, {"class": "4MPHRG", "term": 4}], "MSc (Psychology- Health and Wellbeing)": [{"class": "2MPHW", "term": 2}, {"class": "4MPHW", "term": 4}], "Master of Science (Neuropsychology)": [{"class": "2MPNP", "term": 2}, {"class": "4MPNP", "term": 4}], "Master of Science (Educational Psychology)": [{"class": "2MSEDP", "term": 2}, {"class": "4MSEDP", "term": 4}], "PG Diploma in Counselling Psychology - Bangalore Central Campus": [{"class": "2PGDCP", "term": 2}], "BA Psychology (Honours) - Bangalore Central Campus": [{"class": "8BAPSY(H) BCC", "term": 8}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SCHOOL OF EDUCATION', E'SCHOOL OF PSYCHOLOGICAL SCIENCES, EDUCATION AND SOCIAL WORK', '{"Bachelor of Education": [{"class": "2BEd A", "term": 2}, {"class": "2BEd B", "term": 2}, {"class": "4BEd A", "term": 4}, {"class": "4BEd B", "term": 4}], "Post Graduate Diploma in International Education(PGDIE)": [{"class": "2PGDIE", "term": 2}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SCHOOL OF LAW', E'SCHOOL OF LAW', '{"BA LLB (Honours)": [{"class": "10BALLB A", "term": 10}, {"class": "10BALLB B", "term": 10}, {"class": "10BALLB C", "term": 10}, {"class": "2BALLB A", "term": 2}, {"class": "2BALLB B", "term": 2}, {"class": "2BALLB C", "term": 2}, {"class": "4BALLB A", "term": 4}, {"class": "4BALLB B", "term": 4}, {"class": "4BALLB C", "term": 4}, {"class": "6BALLB A", "term": 6}, {"class": "6BALLB B", "term": 6}, {"class": "6BALLB C", "term": 6}, {"class": "8BALLB A", "term": 8}, {"class": "8BALLB B", "term": 8}, {"class": "8BALLB C", "term": 8}], "BBA LLB (Honours)": [{"class": "10BBALLB A", "term": 10}, {"class": "10BBALLB B", "term": 10}, {"class": "2BBALLB A", "term": 2}, {"class": "2BBALLB B", "term": 2}, {"class": "2BBALLB C", "term": 2}, {"class": "4BBALLB A", "term": 4}, {"class": "4BBALLB B", "term": 4}, {"class": "6BBALLB A", "term": 6}, {"class": "6BBALLB B", "term": 6}, {"class": "8BBALLB A", "term": 8}, {"class": "8BBALLB B", "term": 8}], "Master of Law (LLM) in Constitutional and Administrative Law": [{"class": "2LLMCAL", "term": 2}], "Master of Law (LLM) in Corporate and Commercial Law": [{"class": "2LLMCCL", "term": 2}], "Master of Law (LLM) in Intellectual Property and Trade Law": [{"class": "2LLMIPL", "term": 2}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SOCIAL WORK', E'SCHOOL OF PSYCHOLOGICAL SCIENCES, EDUCATION AND SOCIAL WORK', '{"MSW Clinical and Community Practice": [{"class": "2MSWCC", "term": 2}, {"class": "4MSWCC", "term": 4}], "MSW Human Resources Development and Management": [{"class": "2MSWHR", "term": 2}, {"class": "4MSWHR", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'SOCIOLOGY', E'SCHOOL OF SOCIAL SCIENCES', '{"BA (Economics, Sociology) - Bangalore Central Campus": [{"class": "2BAES", "term": 2}, {"class": "4BAES", "term": 4}, {"class": "6BAES", "term": 6}], "MA Applied Sociology": [{"class": "2MSOC", "term": 2}, {"class": "4MSOC", "term": 4}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'STATISTICS AND DATA SCIENCE', E'SCHOOL OF SCIENCES', '{"BSc (Data Science, Mathematics) - Bangalore Central Campus": [{"class": "2BScDM", "term": 2}, {"class": "4BScDM", "term": 4}, {"class": "6BScDM", "term": 6}], "BSc (Data Science, Statistics) - Bangalore Central Campus": [{"class": "2BScDS", "term": 2}, {"class": "4BScDS", "term": 4}, {"class": "6BScDS", "term": 6}], "Master of Science (Data Science)": [{"class": "2MDS", "term": 2}, {"class": "4MDS", "term": 4}, {"class": "6MDS", "term": 6}], "MSc (Computational Statistics and Applied AI)": [{"class": "2MSCSA AI", "term": 2}, {"class": "4MSCSA AI", "term": 4}], "MSc Data Analytics and Artificial Intelligence and MA Data Analytics and Artificial Intelligence (Steinbeis University, Germany) - Bangalore Central Campus": [{"class": "2MSD A&A", "term": 2}], "MSc (Statistics)": [{"class": "2MSTAT", "term": 2}, {"class": "4MSTAT", "term": 4}, {"class": "6MSTAT", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;
INSERT INTO public.departments_courses (department_name, school, courses_json) VALUES (E'THEATRE STUDIES', E'SCHOOL OF HUMANITIES AND PERFORMING ARTS', '{"BA (Theatre Studies, Creative Media) - Bangalore Central Campus": [{"class": "2BATC", "term": 2}, {"class": "4BATC", "term": 4}, {"class": "6BATC", "term": 6}], "BA (Theatre Studies, Psychology) - Bangalore Central Campus": [{"class": "2BATP", "term": 2}, {"class": "4BATP", "term": 4}, {"class": "6BATP", "term": 6}]}'::jsonb) ON CONFLICT DO NOTHING;

-- ===========================================================================
-- Auto-updated timestamps for departments_courses
-- ===========================================================================

drop trigger if exists trg_departments_courses_updated_at on public.departments_courses;
create trigger trg_departments_courses_updated_at
before update on public.departments_courses
for each row execute function public.set_updated_at();

-- ===== END 004_departments_courses_data.sql =====

-- ===== BEGIN 005_link_users_to_departments.sql =====
-- Migration: 005_link_users_to_departments.sql
-- Purpose: Add department link to users table
-- Date: 2026-04-02
--
-- This adds the ability for users to be linked to their department,
-- which includes all their course information in JSON format.

-- Add department_id foreign key to users table
alter table if exists public.users
add column if not exists department_id uuid;

-- Add foreign key constraint to link users to departments_courses
alter table if exists public.users
add constraint if not exists fk_users_department
  foreign key (department_id)
  references public.departments_courses(id)
  on update cascade
  on delete set null;

-- Create index for department lookups
create index if not exists idx_users_department_id on public.users(department_id);

-- Document: Once a user sets their department, they get access to:
-- 1. All courses in that department (from courses_json)
-- 2. Class details (room, block, term)
-- 3. School information
-- 
-- Example query to get a user's courses:
-- SELECT dc.department_name, dc.courses_json 
-- FROM users u
-- JOIN departments_courses dc ON u.department_id = dc.id
-- WHERE u.id = '[user_id]';

-- ===== END 005_link_users_to_departments.sql =====

-- ===== BEGIN 006_add_notification_user_status.sql =====
-- Migration: Add notification_user_status table for tracking per-user notification read status
-- Date: 2026-04-02
-- Purpose: Track which users have read/dismissed broadcast notifications
-- This table is CRITICAL for notifications to persist across page refreshes/logouts

create table if not exists public.notification_user_status (
  id uuid primary key default gen_random_uuid(),
  notification_id uuid not null,
  user_email text not null,
  is_read boolean not null default false,
  is_dismissed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Ensure one read status record per user per notification
  constraint fk_notification_user_status_notification_id
    foreign key (notification_id)
    references public.notifications(id)
    on delete cascade,

  -- Unique constraint: one entry per user per notification
  constraint uq_notification_user_status_user_notification
    unique (notification_id, user_email)
);

-- Indexes for fast lookups
create index if not exists idx_notification_user_status_user_email 
on public.notification_user_status(user_email);

create index if not exists idx_notification_user_status_notification_id 
on public.notification_user_status(notification_id);

create index if not exists idx_notification_user_status_is_read 
on public.notification_user_status(is_read) 
where is_read = false;

-- Enable RLS
alter table public.notification_user_status enable row level security;

-- Allow all access (tighten later if needed)
drop policy if exists "Allow all access to notification_user_status" on public.notification_user_status;
create policy "Allow all access to notification_user_status" 
on public.notification_user_status for all using (true) with check (true);

-- Auto update updated_at timestamp
create or replace function public.set_notification_user_status_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_notification_user_status_updated_at on public.notification_user_status;
create trigger trg_notification_user_status_updated_at
before update on public.notification_user_status
for each row execute function public.set_notification_user_status_updated_at();

-- Migration note for tracking
comment on table public.notification_user_status is 
'Tracks per-user read/dismiss status for broadcast notifications. Critical for notif persistence.';
-- ===== END 006_add_notification_user_status.sql =====

-- ===== BEGIN 007_fix_notifications_schema.sql =====
-- Fix notifications schema for broadcast support

-- Step 1: Add is_broadcast column if it doesn't exist
ALTER TABLE notifications 
ADD COLUMN IF NOT EXISTS is_broadcast BOOLEAN DEFAULT false;

-- Step 2: Create notification_user_status table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.notification_user_status (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  is_dismissed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Step 3: Create indexes
CREATE INDEX IF NOT EXISTS idx_notification_user_status_user_email 
  ON public.notification_user_status(user_email);

CREATE INDEX IF NOT EXISTS idx_notification_user_status_notification_id 
  ON public.notification_user_status(notification_id);

-- Step 4: Enable RLS
ALTER TABLE public.notification_user_status ENABLE ROW LEVEL SECURITY;

-- Step 5: Drop and recreate policy (safer than IF NOT EXISTS which isn't supported)
DROP POLICY IF EXISTS "Allow all access to notification_user_status" 
  ON public.notification_user_status;

CREATE POLICY "Allow all access to notification_user_status" 
  ON public.notification_user_status FOR ALL USING (true) WITH CHECK (true);
-- ===== END 007_fix_notifications_schema.sql =====

-- ===== BEGIN 008_add_events_on_spot.sql =====
-- Migration: Add on-spot registration toggle for events
-- Purpose: allow event-level override to keep online registrations open after deadline.

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS on_spot BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_events_on_spot ON public.events (on_spot);
-- ===== END 008_add_events_on_spot.sql =====

-- ===== BEGIN 009_add_department_hosted_at.sql =====
-- Migration: Add department_hosted_at field to fests table for department availability control
-- Purpose: Allow fests to specify which department hosts the fest and which departments can register

alter table public.fests add column if not exists department_hosted_at text;

-- Create index for department_hosted_at for faster queries
create index if not exists idx_fests_department_hosted_at on public.fests(department_hosted_at);

-- Confirmation query
SELECT 'fests.department_hosted_at' as column_checked, 
  EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='fests' AND column_name='department_hosted_at') as exists;
-- ===== END 009_add_department_hosted_at.sql =====

-- ===== BEGIN 010_add_fest_custom_fields.sql =====
-- Migration: Add custom_fields to fests for fest-level registration questions
-- Purpose: Enable event-style dynamic custom fields on create/edit fest flows

alter table public.fests
  add column if not exists custom_fields jsonb not null default '[]'::jsonb;

-- Optional index if querying by custom_fields keys later
create index if not exists idx_fests_custom_fields on public.fests using gin(custom_fields);

-- Confirmation query
select 'fests.custom_fields' as column_checked,
  exists(
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'fests'
      and column_name = 'custom_fields'
  ) as exists;
-- ===== END 010_add_fest_custom_fields.sql =====

-- ===== BEGIN 011_complete_database_sync.sql =====
-- Migration: Complete sync for existing SOCIO databases
-- Purpose: bring older databases to the current backend schema expectations in one run.
-- Safe to run multiple times.

create extension if not exists pgcrypto;

-- Canonicalize legacy fest table name if needed.
do $$
begin
  if to_regclass('public.fest') is not null and to_regclass('public.fests') is null then
    alter table public.fest rename to fests;
  end if;
end $$;

-- -----------------------------------------------------------------
-- FESTS
-- -----------------------------------------------------------------
alter table if exists public.fests
  add column if not exists auth_uuid text,
  add column if not exists venue text,
  add column if not exists status text,
  add column if not exists registration_deadline timestamptz,
  add column if not exists organizing_dept text,
  add column if not exists department_access jsonb not null default '[]'::jsonb,
  add column if not exists category text,
  add column if not exists contact_email text,
  add column if not exists contact_phone text,
  add column if not exists event_heads jsonb not null default '[]'::jsonb,
  add column if not exists custom_fields jsonb not null default '[]'::jsonb,
  add column if not exists timeline jsonb not null default '[]'::jsonb,
  add column if not exists sponsors jsonb not null default '[]'::jsonb,
  add column if not exists social_links jsonb not null default '[]'::jsonb,
  add column if not exists faqs jsonb not null default '[]'::jsonb,
  add column if not exists campus_hosted_at text,
  add column if not exists allowed_campuses jsonb not null default '[]'::jsonb,
  add column if not exists department_hosted_at text,
  add column if not exists allow_outsiders boolean not null default false,
  add column if not exists created_by text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz,
  add column if not exists archived_by text;

update public.fests set department_access = '[]'::jsonb where department_access is null;
update public.fests set event_heads = '[]'::jsonb where event_heads is null;
update public.fests set custom_fields = '[]'::jsonb where custom_fields is null;
update public.fests set timeline = '[]'::jsonb where timeline is null;
update public.fests set sponsors = '[]'::jsonb where sponsors is null;
update public.fests set social_links = '[]'::jsonb where social_links is null;
update public.fests set faqs = '[]'::jsonb where faqs is null;
update public.fests set allowed_campuses = '[]'::jsonb where allowed_campuses is null;

alter table if exists public.fests
  alter column department_access set default '[]'::jsonb,
  alter column event_heads set default '[]'::jsonb,
  alter column custom_fields set default '[]'::jsonb,
  alter column timeline set default '[]'::jsonb,
  alter column sponsors set default '[]'::jsonb,
  alter column social_links set default '[]'::jsonb,
  alter column faqs set default '[]'::jsonb,
  alter column allowed_campuses set default '[]'::jsonb;

alter table if exists public.fests
  alter column department_access set not null,
  alter column event_heads set not null,
  alter column custom_fields set not null,
  alter column timeline set not null,
  alter column sponsors set not null,
  alter column social_links set not null,
  alter column faqs set not null,
  alter column allowed_campuses set not null;

-- -----------------------------------------------------------------
-- EVENTS
-- -----------------------------------------------------------------
alter table if exists public.events
  add column if not exists auth_uuid text,
  add column if not exists end_date date,
  add column if not exists fest_id text,
  add column if not exists fest text,
  add column if not exists registration_deadline timestamptz,
  add column if not exists total_participants integer not null default 0,
  add column if not exists custom_fields jsonb not null default '[]'::jsonb,
  add column if not exists allow_outsiders boolean not null default false,
  add column if not exists outsider_registration_fee numeric,
  add column if not exists outsider_max_participants integer,
  add column if not exists campus_hosted_at text,
  add column if not exists allowed_campuses jsonb not null default '[]'::jsonb,
  add column if not exists on_spot boolean not null default false,
  add column if not exists is_archived boolean not null default false,
  add column if not exists archived_at timestamptz,
  add column if not exists archived_by text;

update public.events set custom_fields = '[]'::jsonb where custom_fields is null;
update public.events set allowed_campuses = '[]'::jsonb where allowed_campuses is null;

alter table if exists public.events
  alter column custom_fields set default '[]'::jsonb,
  alter column allowed_campuses set default '[]'::jsonb,
  alter column total_participants set default 0,
  alter column on_spot set default false,
  alter column is_archived set default false;

alter table if exists public.events
  alter column custom_fields set not null,
  alter column allowed_campuses set not null,
  alter column total_participants set not null,
  alter column on_spot set not null,
  alter column is_archived set not null;

-- -----------------------------------------------------------------
-- USERS
-- -----------------------------------------------------------------
alter table if exists public.users
  add column if not exists organization_type text not null default 'christ_member',
  add column if not exists visitor_id text,
  add column if not exists outsider_name_edit_used boolean not null default false,
  add column if not exists campus text,
  add column if not exists organiser_expires_at timestamptz,
  add column if not exists support_expires_at timestamptz,
  add column if not exists masteradmin_expires_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- -----------------------------------------------------------------
-- NOTIFICATION USER STATUS (if older DB does not have it yet)
-- -----------------------------------------------------------------
create table if not exists public.notification_user_status (
  id uuid primary key default gen_random_uuid(),
  notification_id uuid not null,
  user_email text not null,
  is_read boolean not null default false,
  is_dismissed boolean not null default false,
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------
-- INDEXES
-- -----------------------------------------------------------------
do $$
begin
  if to_regclass('public.fests') is not null then
    execute 'create index if not exists idx_fests_created_at on public.fests(created_at desc)';
    execute 'create index if not exists idx_fests_opening_date on public.fests(opening_date desc)';
    execute 'create index if not exists idx_fests_title_lower on public.fests((lower(fest_title)))';
    execute 'create index if not exists idx_fests_dept_lower on public.fests((lower(organizing_dept)))';
    execute 'create index if not exists idx_fests_allow_outsiders on public.fests(allow_outsiders)';
    execute 'create index if not exists idx_fests_department_hosted_at on public.fests(department_hosted_at)';
    execute 'create index if not exists idx_fests_is_archived on public.fests(is_archived)';
    execute 'create index if not exists idx_fests_archived_at on public.fests(archived_at desc)';
    execute 'create index if not exists idx_fests_custom_fields on public.fests using gin(custom_fields)';
  end if;

  if to_regclass('public.events') is not null then
    execute 'create index if not exists idx_events_fest_id on public.events(fest_id)';
    execute 'create index if not exists idx_events_created_at on public.events(created_at desc)';
    execute 'create index if not exists idx_events_event_date on public.events(event_date desc)';
    execute 'create index if not exists idx_events_title_lower on public.events((lower(title)))';
    execute 'create index if not exists idx_events_dept_lower on public.events((lower(organizing_dept)))';
    execute 'create index if not exists idx_events_on_spot on public.events(on_spot)';
    execute 'create index if not exists idx_events_is_archived on public.events(is_archived)';
    execute 'create index if not exists idx_events_archived_at on public.events(archived_at desc)';
    execute 'create index if not exists idx_events_campus_hosted_at on public.events(campus_hosted_at)';
  end if;

  if to_regclass('public.users') is not null then
    execute 'create unique index if not exists idx_users_visitor_id on public.users(visitor_id) where visitor_id is not null';
    execute 'create index if not exists idx_users_email_lower on public.users((lower(email)))';
  end if;

  if to_regclass('public.notification_user_status') is not null then
    execute 'create unique index if not exists idx_notification_user_status_unique on public.notification_user_status(notification_id, user_email)';
    execute 'create index if not exists idx_notification_user_status_user_email on public.notification_user_status(user_email)';
    execute 'create index if not exists idx_notification_user_status_notification_id on public.notification_user_status(notification_id)';
  end if;
end $$;

-- -----------------------------------------------------------------
-- FOREIGN KEYS (added only if absent)
-- -----------------------------------------------------------------
do $$
begin
  if to_regclass('public.events') is not null and to_regclass('public.fests') is not null then
    if not exists (select 1 from pg_constraint where conname = 'fk_events_fest_id') then
      alter table public.events
        add constraint fk_events_fest_id
        foreign key (fest_id)
        references public.fests(fest_id)
        on update cascade
        on delete set null;
    end if;
  end if;

  if to_regclass('public.notification_user_status') is not null and to_regclass('public.notifications') is not null then
    if not exists (select 1 from pg_constraint where conname = 'fk_notification_user_status_notification_id') then
      alter table public.notification_user_status
        add constraint fk_notification_user_status_notification_id
        foreign key (notification_id)
        references public.notifications(id)
        on delete cascade;
    end if;
  end if;
end $$;

-- -----------------------------------------------------------------
-- Quick verification
-- -----------------------------------------------------------------
select 'fests.custom_fields' as check_name,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'fests'
      and column_name = 'custom_fields'
  ) as ok
union all
select 'fests.department_hosted_at' as check_name,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'fests'
      and column_name = 'department_hosted_at'
  ) as ok
union all
select 'events.on_spot' as check_name,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'events'
      and column_name = 'on_spot'
  ) as ok
union all
select 'events.is_archived' as check_name,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'events'
      and column_name = 'is_archived'
  ) as ok;
-- ===== END 011_complete_database_sync.sql =====

-- ===== BEGIN 012_add_event_fest_organizing_school.sql =====
-- Migration: Add organizing school support for events and fests
-- Purpose:
-- 1) add organizing_school columns to events/fests
-- 2) enforce canonical school/department rules without adding new tables
-- 3) keep "Clubs and Centres" flexible for custom department names

-- -----------------------------------------------------------------
-- Add columns on existing tables only
-- -----------------------------------------------------------------
alter table if exists public.events
  add column if not exists organizing_school text;

alter table if exists public.fests
  add column if not exists organizing_school text;

-- -----------------------------------------------------------------
-- Backfill organizing_school from existing organizing_dept
-- -----------------------------------------------------------------
update public.events
set organizing_school = case
  when lower(btrim(organizing_dept)) in (
    'department of business and management (bba)',
    'department of business and management (mba)',
    'department of hotel management'
  ) then 'School of Business and Management'
  when lower(btrim(organizing_dept)) in (
    'department of commerce',
    'department of professional studies'
  ) then 'School of Commerce Finance and Accountancy'
  when lower(btrim(organizing_dept)) in (
    'department of english and cultural studies',
    'department of music',
    'department of performing arts',
    'department of philosophy and theology',
    'department of theatre studies'
  ) then 'School of Humanities and Performing Arts'
  when lower(btrim(organizing_dept)) in (
    'department of law',
    'department of school of law'
  ) then 'School of Law'
  when lower(btrim(organizing_dept)) in (
    'department of psychology',
    'department of education',
    'department of school of education',
    'department of social work'
  ) then 'School of Psychological Sciences, Education and Social Work'
  when lower(btrim(organizing_dept)) in (
    'department of chemistry',
    'department of computer science',
    'department of life sciences',
    'department of mathematics',
    'department of physics and electronics',
    'department of statistics and data science'
  ) then 'School of Sciences'
  when lower(btrim(organizing_dept)) in (
    'department of economics',
    'department of international studies, political science and history',
    'department of media studies',
    'department of sociology'
  ) then 'School of Social Sciences'
  when lower(btrim(organizing_dept)) in (
    'student welfare office',
    'national cadet corps',
    'other clubs and centres'
  ) then 'Clubs and Centres'
  else organizing_school
end
where (organizing_school is null or btrim(organizing_school) = '')
  and organizing_dept is not null
  and btrim(organizing_dept) <> '';

update public.fests
set organizing_school = case
  when lower(btrim(organizing_dept)) in (
    'department of business and management (bba)',
    'department of business and management (mba)',
    'department of hotel management'
  ) then 'School of Business and Management'
  when lower(btrim(organizing_dept)) in (
    'department of commerce',
    'department of professional studies'
  ) then 'School of Commerce Finance and Accountancy'
  when lower(btrim(organizing_dept)) in (
    'department of english and cultural studies',
    'department of music',
    'department of performing arts',
    'department of philosophy and theology',
    'department of theatre studies'
  ) then 'School of Humanities and Performing Arts'
  when lower(btrim(organizing_dept)) in (
    'department of law',
    'department of school of law'
  ) then 'School of Law'
  when lower(btrim(organizing_dept)) in (
    'department of psychology',
    'department of education',
    'department of school of education',
    'department of social work'
  ) then 'School of Psychological Sciences, Education and Social Work'
  when lower(btrim(organizing_dept)) in (
    'department of chemistry',
    'department of computer science',
    'department of life sciences',
    'department of mathematics',
    'department of physics and electronics',
    'department of statistics and data science'
  ) then 'School of Sciences'
  when lower(btrim(organizing_dept)) in (
    'department of economics',
    'department of international studies, political science and history',
    'department of media studies',
    'department of sociology'
  ) then 'School of Social Sciences'
  when lower(btrim(organizing_dept)) in (
    'student welfare office',
    'national cadet corps',
    'other clubs and centres'
  ) then 'Clubs and Centres'
  else organizing_school
end
where (organizing_school is null or btrim(organizing_school) = '')
  and organizing_dept is not null
  and btrim(organizing_dept) <> '';

-- -----------------------------------------------------------------
-- Check constraints for allowed school names (no extra table needed)
-- -----------------------------------------------------------------
do $$
begin
  if to_regclass('public.events') is not null then
    if exists (
      select 1
      from pg_constraint
      where conname = 'chk_events_organizing_school_allowed'
        and conrelid = 'public.events'::regclass
    ) then
      alter table public.events
        drop constraint chk_events_organizing_school_allowed;
    end if;

    alter table public.events
      add constraint chk_events_organizing_school_allowed
      check (
        organizing_school is null
        or organizing_school in (
          'School of Business and Management',
          'School of Commerce Finance and Accountancy',
          'School of Humanities and Performing Arts',
          'School of Law',
          'School of Psychological Sciences, Education and Social Work',
          'School of Sciences',
          'School of Social Sciences',
          'Clubs and Centres'
        )
      )
      not valid;

    create index if not exists idx_events_organizing_school
      on public.events(organizing_school);
  end if;

  if to_regclass('public.fests') is not null then
    if exists (
      select 1
      from pg_constraint
      where conname = 'chk_fests_organizing_school_allowed'
        and conrelid = 'public.fests'::regclass
    ) then
      alter table public.fests
        drop constraint chk_fests_organizing_school_allowed;
    end if;

    alter table public.fests
      add constraint chk_fests_organizing_school_allowed
      check (
        organizing_school is null
        or organizing_school in (
          'School of Business and Management',
          'School of Commerce Finance and Accountancy',
          'School of Humanities and Performing Arts',
          'School of Law',
          'School of Psychological Sciences, Education and Social Work',
          'School of Sciences',
          'School of Social Sciences',
          'Clubs and Centres'
        )
      )
      not valid;

    create index if not exists idx_fests_organizing_school
      on public.fests(organizing_school);
  end if;
end $$;

-- -----------------------------------------------------------------
-- Validation trigger:
-- For all schools except Clubs and Centres, organizing_dept must match
-- canonical department list for that selected school.
-- -----------------------------------------------------------------
create or replace function public.validate_school_department_pair()
returns trigger
language plpgsql
as $$
declare
  normalized_school text := btrim(coalesce(new.organizing_school, ''));
  normalized_dept text := btrim(coalesce(new.organizing_dept, ''));
begin
  if normalized_school = '' then
    return new;
  end if;

  if normalized_school not in (
    'School of Business and Management',
    'School of Commerce Finance and Accountancy',
    'School of Humanities and Performing Arts',
    'School of Law',
    'School of Psychological Sciences, Education and Social Work',
    'School of Sciences',
    'School of Social Sciences',
    'Clubs and Centres'
  ) then
    raise exception 'Invalid organizing_school (%)', normalized_school
      using errcode = '23514';
  end if;

  if normalized_dept = '' then
    return new;
  end if;

  if normalized_school = 'Clubs and Centres' then
    return new;
  end if;

  if normalized_school = 'School of Business and Management'
    and normalized_dept not in (
      'Department of Business and Management (BBA)',
      'Department of Business and Management (MBA)',
      'Department of Hotel Management'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  if normalized_school = 'School of Commerce Finance and Accountancy'
    and normalized_dept not in (
      'Department of Commerce',
      'Department of Professional Studies'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  if normalized_school = 'School of Humanities and Performing Arts'
    and normalized_dept not in (
      'Department of English and Cultural Studies',
      'Department of Music',
      'Department of Performing Arts',
      'Department of Philosophy and Theology',
      'Department of Theatre Studies'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  if normalized_school = 'School of Law'
    and normalized_dept not in (
      'Department of Law',
      'Department of School of Law'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  if normalized_school = 'School of Psychological Sciences, Education and Social Work'
    and normalized_dept not in (
      'Department of Psychology',
      'Department of Education',
      'Department of School of Education',
      'Department of Social Work'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  if normalized_school = 'School of Sciences'
    and normalized_dept not in (
      'Department of Chemistry',
      'Department of Computer Science',
      'Department of Life Sciences',
      'Department of Mathematics',
      'Department of Physics and Electronics',
      'Department of Statistics and Data Science'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  if normalized_school = 'School of Social Sciences'
    and normalized_dept not in (
      'Department of Economics',
      'Department of International Studies, Political Science and History',
      'Department of Media Studies',
      'Department of Sociology'
    ) then
    raise exception 'Invalid organizing_dept (%) for organizing_school (%)', normalized_dept, normalized_school
      using errcode = '23514';
  end if;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public.events') is not null then
    drop trigger if exists trg_events_validate_school_department on public.events;
    create trigger trg_events_validate_school_department
      before insert or update of organizing_school, organizing_dept
      on public.events
      for each row
      execute function public.validate_school_department_pair();
  end if;

  if to_regclass('public.fests') is not null then
    drop trigger if exists trg_fests_validate_school_department on public.fests;
    create trigger trg_fests_validate_school_department
      before insert or update of organizing_school, organizing_dept
      on public.fests
      for each row
      execute function public.validate_school_department_pair();
  end if;
end $$;

-- -----------------------------------------------------------------
-- Verification
-- -----------------------------------------------------------------
select 'events.organizing_school' as check_name,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'events'
      and column_name = 'organizing_school'
  ) as ok
union all
select 'fests.organizing_school' as check_name,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'fests'
      and column_name = 'organizing_school'
  ) as ok;
-- ===== END 012_add_event_fest_organizing_school.sql =====

-- ===== BEGIN 013_module11_approval_phase1.sql =====
-- Migration 013: Module 11 Phase 1 – Approval Workflow
-- Adds: new role flags on users, approvals table, workflow_config table
-- Safe to run multiple times (all DDL uses IF NOT EXISTS / IF EXISTS guards)

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------
-- USERS – new approval role flags
-- -----------------------------------------------------------------
alter table if exists public.users
  add column if not exists is_hod             boolean not null default false,
  add column if not exists is_dean            boolean not null default false,
  add column if not exists is_cfo             boolean not null default false,
  add column if not exists is_campus_director boolean not null default false,
  add column if not exists is_accounts_office boolean not null default false,
  add column if not exists is_it_support      boolean not null default false,
  add column if not exists is_vendor_manager  boolean not null default false,
  add column if not exists is_stalls          boolean not null default false,
  add column if not exists school             text;

-- -----------------------------------------------------------------
-- APPROVALS table
-- -----------------------------------------------------------------
create table if not exists public.approvals (
  id                              uuid primary key default gen_random_uuid(),
  event_or_fest_id                text not null,
  type                            text not null check (type in ('event', 'fest')),

  -- Stage 1 blocking steps (column names per spec)
  stage1_hod                      text not null default 'pending'
                                    check (stage1_hod in ('pending','approved','rejected','skipped')),
  stage2_dean                     text not null default 'pending'
                                    check (stage2_dean in ('pending','approved','rejected','skipped')),
  stage3_cfo                      text not null default 'pending'
                                    check (stage3_cfo in ('pending','approved','rejected','skipped')),
  stage4_accounts                 text not null default 'pending'
                                    check (stage4_accounts in ('pending','approved','rejected','skipped')),

  -- Stage 2 operational lanes
  catering_approval               text not null default 'pending'
                                    check (catering_approval in ('pending','approved','rejected','skipped')),
  it_support_approval             text not null default 'pending'
                                    check (it_support_approval in ('pending','approved','rejected','skipped')),
  stalls_approval                 text not null default 'pending'
                                    check (stalls_approval in ('pending','approved','rejected','skipped')),
  venue_approval                  text not null default 'pending'
                                    check (venue_approval in ('pending','approved','rejected','skipped')),
  miscellaneous_approval          text not null default 'pending'
                                    check (miscellaneous_approval in ('pending','approved','rejected','skipped')),

  -- Workflow metadata
  parent_fest_id                  text,
  workflow_version                text not null default 'v1',
  current_stage                   integer not null default 1 check (current_stage in (1, 2)),
  went_live_at                    timestamptz,
  created_at                      timestamptz not null default now(),
  updated_at                      timestamptz not null default now(),
  last_action_by                  text,
  last_action_at                  timestamptz,
  organizing_department_snapshot  text,
  organizing_school_snapshot      text,
  submitted_by                    text,

  -- HOD assignee tracking (Phase 1)
  stage1_hod_assignee_user_id     uuid,
  stage1_hod_routing_state        text not null default 'waiting_for_assignment'
                                    check (stage1_hod_routing_state in ('assigned','waiting_for_assignment')),

  -- Dean assignee tracking (Phase 1)
  stage2_dean_assignee_user_id    uuid,
  stage2_dean_routing_state       text not null default 'waiting_for_assignment'
                                    check (stage2_dean_routing_state in ('assigned','waiting_for_assignment')),

  -- Audit log: array of {step, action, by, byEmail, at, note, is_override}
  action_log                      jsonb not null default '[]'::jsonb,

  unique (event_or_fest_id, type)
);

-- -----------------------------------------------------------------
-- WORKFLOW_CONFIG table (dropdown-driven configuration)
-- -----------------------------------------------------------------
create table if not exists public.workflow_config (
  id                  uuid primary key default gen_random_uuid(),
  step_key            text unique not null,
  step_label          text not null,
  stage_bucket        integer not null check (stage_bucket in (1, 2)),
  order_index         integer not null,
  is_blocking         boolean not null default true,
  applies_to          text[] not null default array['fest','standalone_event','under_fest_event'],
  can_inherit_from_fest boolean not null default false,
  enabled             boolean not null default true
);

-- Seed default workflow config (skip if rows already exist)
insert into public.workflow_config (step_key, step_label, stage_bucket, order_index, is_blocking, applies_to, can_inherit_from_fest, enabled)
select step_key, step_label, stage_bucket, order_index, is_blocking, applies_to, can_inherit_from_fest, enabled
from (values
  ('hod',        'HOD',              1, 1, true,  array['fest','standalone_event']::text[],                            false, true),
  ('dean',       'Dean',             1, 2, true,  array['fest','standalone_event']::text[],                            false, true),
  ('cfo',        'CFO/Campus Dir',   1, 3, true,  array['fest','standalone_event']::text[],                            false, true),
  ('accounts',   'Accounts Office',  1, 4, true,  array['fest','standalone_event']::text[],                            false, true),
  ('it',         'IT Support',       2, 1, false, array['fest','standalone_event','under_fest_event']::text[],         true,  true),
  ('venue',      'Venue',            2, 2, false, array['fest','standalone_event','under_fest_event']::text[],         true,  true),
  ('catering',   'Catering Vendors', 2, 3, false, array['fest','standalone_event','under_fest_event']::text[],         true,  true),
  ('stalls',     'Stalls/Misc',      2, 4, false, array['fest','standalone_event','under_fest_event']::text[],         true,  true),
  ('volunteers', 'Volunteers',       2, 5, false, array['fest','standalone_event','under_fest_event']::text[],         true,  true)
) as v(step_key, step_label, stage_bucket, order_index, is_blocking, applies_to, can_inherit_from_fest, enabled)
where not exists (select 1 from public.workflow_config where workflow_config.step_key = v.step_key);

-- -----------------------------------------------------------------
-- INDEXES
-- -----------------------------------------------------------------
do $$
begin
  if to_regclass('public.users') is not null then
    execute 'create index if not exists idx_users_is_hod  on public.users(is_hod)  where is_hod  = true';
    execute 'create index if not exists idx_users_is_dean on public.users(is_dean) where is_dean = true';
    execute 'create index if not exists idx_users_school  on public.users(school)  where school  is not null';
  end if;

  if to_regclass('public.approvals') is not null then
    execute 'create index if not exists idx_approvals_event_or_fest_id on public.approvals(event_or_fest_id)';
    execute 'create index if not exists idx_approvals_type             on public.approvals(type)';
    execute 'create index if not exists idx_approvals_parent_fest_id  on public.approvals(parent_fest_id) where parent_fest_id is not null';
    execute 'create index if not exists idx_approvals_current_stage   on public.approvals(current_stage)';
    execute 'create index if not exists idx_approvals_stage1_hod      on public.approvals(stage1_hod)';
    execute 'create index if not exists idx_approvals_stage2_dean     on public.approvals(stage2_dean)';
    execute 'create index if not exists idx_approvals_submitted_by    on public.approvals(submitted_by)';
    execute 'create index if not exists idx_approvals_hod_assignee    on public.approvals(stage1_hod_assignee_user_id) where stage1_hod_assignee_user_id is not null';
    execute 'create index if not exists idx_approvals_dean_assignee   on public.approvals(stage2_dean_assignee_user_id) where stage2_dean_assignee_user_id is not null';
    execute 'create index if not exists idx_approvals_hod_routing     on public.approvals(stage1_hod_routing_state)';
    execute 'create index if not exists idx_approvals_dean_routing    on public.approvals(stage2_dean_routing_state)';
  end if;
end $$;

-- -----------------------------------------------------------------
-- Verification
-- -----------------------------------------------------------------
select 'users.is_hod' as check_name,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'is_hod'
  ) as ok
union all
select 'approvals table' as check_name,
  exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'approvals'
  ) as ok
union all
select 'workflow_config table' as check_name,
  exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'workflow_config'
  ) as ok;
-- ===== END 013_module11_approval_phase1.sql =====

-- ===== BEGIN 014_dynamic_stages.sql =====
-- Migration 014: Dynamic JSONB stages array
-- Replaces 13 hardcoded approval-role columns with a single `stages` jsonb array.
-- Each element: { step, role, label, status, assignee_user_id, routing_state, blocking }
-- Safe to run in Supabase SQL Editor as a single transaction.

begin;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add stages column (nullable during backfill)
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.approvals
  add column if not exists stages jsonb;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Backfill existing rows from old columns into stages array
--    Preserves hod/dean assignee UUIDs and routing states.
--    CFO/accounts/stage2 lanes had no assignee tracking → null.
-- ─────────────────────────────────────────────────────────────────────────────

update public.approvals
set stages = jsonb_build_array(
  jsonb_build_object(
    'step',             0,
    'role',             'hod',
    'label',            'HOD',
    'status',           stage1_hod,
    'assignee_user_id', stage1_hod_assignee_user_id::text,
    'routing_state',    stage1_hod_routing_state,
    'blocking',         true
  ),
  jsonb_build_object(
    'step',             1,
    'role',             'dean',
    'label',            'Dean',
    'status',           stage2_dean,
    'assignee_user_id', stage2_dean_assignee_user_id::text,
    'routing_state',    stage2_dean_routing_state,
    'blocking',         true
  ),
  jsonb_build_object(
    'step',             2,
    'role',             'cfo',
    'label',            'CFO/Campus Dir',
    'status',           stage3_cfo,
    'assignee_user_id', null,
    'routing_state',    case when stage3_cfo = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         true
  ),
  jsonb_build_object(
    'step',             3,
    'role',             'accounts',
    'label',            'Accounts Office',
    'status',           stage4_accounts,
    'assignee_user_id', null,
    'routing_state',    case when stage4_accounts = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         true
  ),
  jsonb_build_object(
    'step',             4,
    'role',             'it',
    'label',            'IT Support',
    'status',           it_support_approval,
    'assignee_user_id', null,
    'routing_state',    case when it_support_approval = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         false
  ),
  jsonb_build_object(
    'step',             5,
    'role',             'venue',
    'label',            'Venue',
    'status',           venue_approval,
    'assignee_user_id', null,
    'routing_state',    case when venue_approval = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         false
  ),
  jsonb_build_object(
    'step',             6,
    'role',             'catering',
    'label',            'Catering Vendors',
    'status',           catering_approval,
    'assignee_user_id', null,
    'routing_state',    case when catering_approval = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         false
  ),
  jsonb_build_object(
    'step',             7,
    'role',             'stalls',
    'label',            'Stalls/Misc',
    'status',           stalls_approval,
    'assignee_user_id', null,
    'routing_state',    case when stalls_approval = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         false
  ),
  jsonb_build_object(
    'step',             8,
    'role',             'miscellaneous',
    'label',            'Miscellaneous',
    'status',           miscellaneous_approval,
    'assignee_user_id', null,
    'routing_state',    case when miscellaneous_approval = 'pending' then 'waiting_for_assignment' else 'assigned' end,
    'blocking',         false
  )
)
where stages is null;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Make stages NOT NULL with default
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.approvals
  alter column stages set not null,
  alter column stages set default '[]'::jsonb;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Drop old hardcoded columns
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.approvals
  drop column if exists stage1_hod,
  drop column if exists stage2_dean,
  drop column if exists stage3_cfo,
  drop column if exists stage4_accounts,
  drop column if exists catering_approval,
  drop column if exists it_support_approval,
  drop column if exists stalls_approval,
  drop column if exists venue_approval,
  drop column if exists miscellaneous_approval,
  drop column if exists stage1_hod_assignee_user_id,
  drop column if exists stage1_hod_routing_state,
  drop column if exists stage2_dean_assignee_user_id,
  drop column if exists stage2_dean_routing_state,
  drop column if exists current_stage;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Drop old indexes that referenced dropped columns
-- ─────────────────────────────────────────────────────────────────────────────

drop index if exists public.idx_approvals_current_stage;
drop index if exists public.idx_approvals_stage1_hod;
drop index if exists public.idx_approvals_stage2_dean;
drop index if exists public.idx_approvals_hod_assignee;
drop index if exists public.idx_approvals_dean_assignee;
drop index if exists public.idx_approvals_hod_routing;
drop index if exists public.idx_approvals_dean_routing;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Add GIN index for JSONB containment queries (@>)
-- ─────────────────────────────────────────────────────────────────────────────

create index if not exists idx_approvals_stages_gin
  on public.approvals using gin (stages);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Postgres RPC for bulk auto-routing (called from userRoutes.js)
--    Updates all waiting_for_assignment stage objects matching p_role + p_school
--    to assigned in a single query instead of JS read-modify-write loop.
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.route_approvals_to_user(
  p_user_id   uuid,
  p_role      text,
  p_school    text
) returns integer
language plpgsql
security definer
as $$
declare
  v_row   record;
  v_new   jsonb;
  v_count integer := 0;
begin
  for v_row in
    select id, stages
    from public.approvals
    where organizing_school_snapshot = p_school
      and stages @> jsonb_build_array(
            jsonb_build_object(
              'role',          p_role,
              'status',        'pending',
              'routing_state', 'waiting_for_assignment'
            )
          )
  loop
    select jsonb_agg(
      case
        when (elem->>'role') = p_role
         and (elem->>'routing_state') = 'waiting_for_assignment'
         and (elem->>'status') = 'pending'
        then elem
          || jsonb_build_object(
               'assignee_user_id', p_user_id::text,
               'routing_state',    'assigned'
             )
        else elem
      end
      order by (elem->>'step')::int
    )
    into v_new
    from jsonb_array_elements(v_row.stages) as elem;

    update public.approvals
    set stages     = v_new,
        updated_at = now()
    where id = v_row.id;

    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. Verification
-- ─────────────────────────────────────────────────────────────────────────────

select 'stages column exists'    as check_name,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'approvals' and column_name = 'stages'
  ) as ok
union all
select 'old columns dropped',
  not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'approvals'
      and column_name in ('stage1_hod', 'current_stage', 'catering_approval')
  )
union all
select 'all rows backfilled',
  not exists (
    select 1 from public.approvals where stages is null
  )
union all
select 'rpc function exists',
  exists (
    select 1 from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'route_approvals_to_user'
  );

commit;
-- ===== END 014_dynamic_stages.sql =====

-- ===== BEGIN 015_campus_dept_matching.sql =====
-- Migration 015: Campus matching for approval routing
-- Safe to re-run — all statements are idempotent.

begin;

alter table public.approvals
  add column if not exists organizing_campus_snapshot text;

drop index if exists idx_approvals_campus_snapshot;
drop index if exists idx_users_department;
drop index if exists idx_users_campus;

create index idx_approvals_campus_snapshot on approvals (organizing_campus_snapshot);
create index idx_users_department           on users     (department);
create index idx_users_campus               on users     (campus);

select 'organizing_campus_snapshot on approvals' as check_name,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'approvals'
      and column_name = 'organizing_campus_snapshot'
  ) as ok
union all
select 'department column exists on users',
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users'
      and column_name = 'department'
  );

commit;
-- ===== END 015_campus_dept_matching.sql =====

-- ===== BEGIN 016_approval_budget_items.sql =====
-- Migration 016: Budget items on approval records
-- Stores the organiser's expense estimate submitted with the approval request.

begin;

alter table public.approvals
  add column if not exists budget_items jsonb not null default '[]';

select 'budget_items on approvals' as check_name,
  exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'approvals'
      and column_name = 'budget_items'
  ) as ok;

commit;
-- ===== END 016_approval_budget_items.sql =====

