// Centralized data for all centres and clubs

export interface Centre {
  id: number;
  slug: string;
  title: string;
  subtitle?: string;
  description: string;
  externalLink?: string;
  image?: string;
  category: string;
}

export const allCentres: Centre[] = [
  {
    id: 1,
    slug: "cnri",
    title: "CNRI",
    subtitle: "Centre for Neurodiversity Research and Innovation",
    description: "Enhances understanding and support for neurodiverse individuals by fostering research and innovation, creating inclusive environments, and advancing societal awareness and acceptance.",
    externalLink: "https://christuniversity.in/center/C/cnri",
    image: "https://christuniversity.in/uploads/centers/thumb/472543836_2024-02-08_04-05-53.jpg",
    category: "Research",
  },
  {
    id: 2,
    slug: "caps",
    title: "CAPS",
    subtitle: "Centre for Academic and Professional Support",
    description: "Provides academic and professional training, resources, and talks designed to support students' academic excellence and career development with workshops on various skills.",
    externalLink: "https://caps.christuniversity.in/",
    image: "https://christuniversity.in/uploads/centers/thumb/399194325_2023-07-11_06-36-56.jpg",
    category: "Academic",
  },
  {
    id: 3,
    slug: "card",
    title: "CARD",
    subtitle: "Centre for Advanced Research and Development",
    description: "Focuses on advancing research in various disciplines by providing resources, facilities, and support for innovative research projects that contribute to academic knowledge and societal development.",
    externalLink: "https://christuniversity.in/center/C/card",
    image: "https://christuniversity.in/uploads/centers/thumb/1464799697_2023-06-16_10-20-28.jpg",
    category: "Research",
  },
  {
    id: 4,
    slug: "cai",
    title: "CAI",
    subtitle: "Centre for Artificial Intelligence",
    description: "Dedicated to advancing education, research, and innovation in artificial intelligence, focusing on practical applications of AI technologies in industries and academia.",
    externalLink: "https://christuniversity.in/center/C/Centre-forArtificialIntelligence",
    image: "https://christuniversity.in/uploads/centers/thumb/826197872_2023-07-11_06-30-37.jpg",
    category: "Innovation",
  },
  {
    id: 5,
    slug: "ccrd",
    title: "CCRD",
    subtitle: "Centre for Case Research and Development",
    description: "Develops comprehensive case studies across disciplines, enhancing teaching effectiveness through real-world business scenarios and facilitating case-based learning and research.",
    externalLink: "https://christuniversity.in/center/C/Centre-for-Case-Research-and-Development-",
    image: "https://christuniversity.in/uploads/centers/thumb/1739624898_2023-06-16_09-51-59.jpg",
    category: "Academic",
  },
  {
    id: 6,
    slug: "ccd",
    title: "CCD",
    subtitle: "Centre for Concept Design",
    description: "Emphasizes effective communication through media, content, and digital services, nurturing creativity and providing tools to conceptualize and design innovative digital media projects.",
    externalLink: "https://christuniversity.in/center/C/CCD",
    image: "https://christuniversity.in/uploads/centers/thumb/1134426620_2023-06-16_09-34-34.jpg",
    category: "Innovation",
  },
  {
    id: 7,
    slug: "cchs",
    title: "CCHS",
    subtitle: "Centre for Counselling and Health Services",
    description: "Offers services to support mental and physical well-being of students including counseling sessions, mental health awareness programs, and professional health support.",
    externalLink: "https://christuniversity.in/center/C/CCHS",
    image: "https://christuniversity.in/uploads/centers/thumb/474773062_2023-06-16_09-24-32.jpg",
    category: "Student support",
  },
  {
    id: 8,
    slug: "cdi",
    title: "CDI",
    subtitle: "Centre for Digital Innovation",
    description: "Fosters digital innovation through cutting-edge technology exploration, encouraging students and faculty to develop innovative digital solutions for real-world challenges.",
    externalLink: "https://christuniversity.in/center/C/CDI",
    image: "https://christuniversity.in/uploads/centers/thumb/757176875_2023-06-16_09-14-38.jpg",
    category: "Innovation",
  },
  {
    id: 9,
    slug: "ceas",
    title: "CEAS",
    subtitle: "Centre for East Asian Studies",
    description: "Promotes understanding of East Asian cultures, languages, and societies through academic programs, cultural exchanges, and research collaborations with East Asian institutions.",
    externalLink: "https://ceas.christuniversity.in/",
    image: "https://christuniversity.in/uploads/centers/thumb/845100346_2023-06-16_09-06-11.jpg",
    category: "Cultural",
  },
  {
    id: 10,
    slug: "cedbec",
    title: "CEDBEC",
    subtitle: "Centre for Education Beyond Curriculum",
    description: "Enhances student learning beyond traditional curriculum through workshops, seminars, and experiential learning opportunities that develop critical thinking and practical skills.",
    externalLink: "https://christuniversity.in/center/C/CEDBEC",
    image: "https://christuniversity.in/uploads/centers/thumb/1448228427_2023-06-16_08-46-12.jpg",
    category: "Academic",
  },
  {
    id: 11,
    slug: "cedric",
    title: "CEDRIC",
    subtitle: "Centre for Establishing, Developing, and Research in Incubation Centres",
    description: "Supports entrepreneurial initiatives by providing resources, mentorship, and infrastructure for startups, fostering innovation and business development within the university ecosystem.",
    externalLink: "https://christuniversity.in/center/C/cedric",
    image: "https://christuniversity.in/uploads/centers/thumb/304659937_2023-06-16_06-57-01.jpg",
    category: "Innovation",
  },
  {
    id: 12,
    slug: "cfpr",
    title: "CFPR",
    subtitle: "Centre for Fiscal Policy Research",
    description: "Conducts research on fiscal policies and economic trends, providing insights and recommendations for policymakers, academics, and the public on financial and economic issues.",
    externalLink: "https://christuniversity.in/center/C/cfpr",
    image: "https://christuniversity.in/uploads/centers/thumb/1042458721_2023-06-16_06-43-44.jpg",
    category: "Research",
  },
  {
    id: 13,
    slug: "cis",
    title: "CIS",
    subtitle: "Centre for International Studies",
    description: "Promotes global engagement through international academic collaborations, exchange programs, and research partnerships, enhancing the university's global presence and perspective.",
    externalLink: "https://christuniversity.in/center/C/CIS",
    image: "https://christuniversity.in/uploads/centers/thumb/2130509750_2023-06-16_06-20-01.jpg",
    category: "Academic",
  },
  {
    id: 14,
    slug: "clgt",
    title: "CLGT",
    subtitle: "Centre for Leadership and Governance Transformation",
    description: "Develops effective leadership skills and governance practices through training programs, workshops, and research aimed at transforming individuals into responsible leaders.",
    externalLink: "https://christuniversity.in/center/C/CLGT",
    image: "https://christuniversity.in/uploads/centers/thumb/1758958172_2023-06-16_05-41-48.jpg",
    category: "Leadership",
  },
  {
    id: 15,
    slug: "cmtp",
    title: "CMTP",
    subtitle: "Centre for Modern Technologies and Practices",
    description: "Explores and integrates modern technologies and innovative practices into academic and administrative processes, enhancing efficiency and effectiveness across the university.",
    externalLink: "https://christuniversity.in/center/C/centre-for-modern-technologies-and-practices-cmtp",
    image: "https://christuniversity.in/uploads/centers/thumb/798694573_2023-06-16_05-27-37.jpg",
    category: "Innovation",
  },
  {
    id: 16,
    slug: "cmrp",
    title: "CMRP",
    subtitle: "Centre for Management Research and Projects",
    description: "Facilitates management research and project-based learning, connecting academic knowledge with real-world management practices and business challenges.",
    externalLink: "https://christuniversity.in/center/C/cmrp",
    image: "https://christuniversity.in/uploads/centers/thumb/1555158781_2023-06-16_05-16-57.jpg",
    category: "Research",
  },
  {
    id: 17,
    slug: "cpe",
    title: "CPE",
    subtitle: "Centre for Professional Excellence",
    description: "Enhances professional competencies through specialized training programs, industry collaborations, and skill development initiatives that prepare students for successful careers.",
    externalLink: "https://christuniversity.in/center/C/CPE",
    image: "https://christuniversity.in/uploads/centers/thumb/2086186414_2023-06-16_05-04-48.jpg",
    category: "Academic",
  },
  {
    id: 18,
    slug: "cpfa",
    title: "CPFA",
    subtitle: "Centre for Professional Fine Arts",
    description: "Nurtures artistic talents and creative expression through fine arts programs, exhibitions, and workshops that develop aesthetic sensibilities and professional artistic skills.",
    externalLink: "https://christuniversity.in/center/C/cpfa",
    image: "https://christuniversity.in/uploads/centers/thumb/1576222968_2023-06-16_04-45-23.jpg",
    category: "Cultural",
  },
  {
    id: 19,
    slug: "cpsa",
    title: "CPSA",
    subtitle: "Centre for Professional Skills and Activities",
    description: "Focuses on developing essential professional skills through practical training, activities, and workshops that enhance employability and workplace readiness.",
    externalLink: "https://christuniversity.in/center/C/cpsa",
    image: "https://christuniversity.in/uploads/centers/thumb/1822230593_2023-06-16_04-25-28.jpg",
    category: "Academic",
  },
  {
    id: 20,
    slug: "crcdc",
    title: "CRCDC",
    subtitle: "Centre for Resource & Curriculum Development for Communication",
    description: "Develops innovative curriculum and resources for communication studies, enhancing teaching methodologies and learning materials for effective communication education.",
    externalLink: "https://christuniversity.in/center/C/centre-for-resource-curriculum-development-for-communication-crcdc",
    image: "https://christuniversity.in/uploads/centers/thumb/1831788784_2023-06-16_04-09-24.jpg",
    category: "Academic",
  },
  {
    id: 21,
    slug: "crsl",
    title: "CRSL",
    subtitle: "Centre for Research in Social Innovation and Leadership",
    description: "Promotes research and initiatives focused on social innovation and leadership development, addressing societal challenges through innovative leadership approaches.",
    externalLink: "https://christuniversity.in/center/C/crsl",
    image: "https://christuniversity.in/uploads/centers/thumb/806621914_2023-06-16_03-51-33.jpg",
    category: "Social",
  },
  {
    id: 22,
    slug: "csa",
    title: "CSA",
    subtitle: "Centre for Social Action",
    description: "Engages in community service and social responsibility initiatives, encouraging students to contribute to society through various outreach programs and volunteer activities.",
    externalLink: "https://christuniversity.in/center/C/CSA",
    image: "https://christuniversity.in/uploads/centers/thumb/91103435_2023-06-16_03-32-05.jpg",
    category: "Social",
  },
  {
    id: 23,
    slug: "csed",
    title: "CSED",
    subtitle: "Centre for Software Engineering and Development",
    description: "Focuses on software engineering principles and practices, developing innovative software solutions and providing expertise in software development methodologies.",
    externalLink: "https://christuniversity.in/center/C/csed",
    image: "https://christuniversity.in/uploads/centers/thumb/1193308951_2023-06-16_03-15-35.jpg",
    category: "Innovation",
  },
  {
    id: 24,
    slug: "ctit",
    title: "CTIT",
    subtitle: "Centre for Technology in Teaching and Testing",
    description: "Integrates technology into teaching and assessment processes, enhancing educational delivery through innovative technological tools and digital assessment methods.",
    externalLink: "https://ctit.christuniversity.in/",
    image: "https://christuniversity.in/uploads/centers/thumb/685376776_2023-06-16_02-48-47.jpg",
    category: "Academic",
  },
  {
    id: 25,
    slug: "ctil",
    title: "CTIL",
    subtitle: "Centre for Technology Innovation Lab",
    description: "Provides a platform for technological innovation and experimentation, encouraging students to develop new technologies and solutions for various applications.",
    externalLink: "https://christuniversity.in/center/C/CTIL",
    image: "https://christuniversity.in/uploads/centers/thumb/696573225_2023-06-16_02-26-04.jpg",
    category: "Innovation",
  },
  {
    id: 26,
    slug: "ctms",
    title: "CTMS",
    subtitle: "Centre for Test Management and Standardization",
    description: "Ensures quality and standardization in testing and assessment methodologies, developing reliable evaluation systems for measuring student learning outcomes.",
    externalLink: "https://christuniversity.in/center/C/CTMS",
    image: "https://christuniversity.in/uploads/centers/thumb/589231854_2023-06-16_02-07-49.jpg",
    category: "Academic",
  },
  {
    id: 27,
    slug: "cwe",
    title: "CWE",
    subtitle: "Centre for Wellness Education",
    description: "Promotes holistic well-being through wellness education programs, activities, and initiatives that address physical, mental, and emotional health of the university community.",
    externalLink: "https://christuniversity.in/center/C/CWE",
    image: "https://christuniversity.in/uploads/centers/thumb/1987413024_2023-06-14_09-59-16.jpg",
    category: "Student support",
  },
  {
    id: 28,
    slug: "cwsr",
    title: "CWSR",
    subtitle: "Centre for Women's Studies and Research",
    description: "Focuses on gender studies, women's empowerment, and research addressing gender-related issues, promoting equality and understanding through academic programs and advocacy.",
    externalLink: "https://christuniversity.in/center/C/cwsr",
    image: "https://christuniversity.in/uploads/centers/thumb/1393908217_2023-06-14_09-42-15.jpg",
    category: "Research",
  },
  {
    id: 29,
    slug: "ichr",
    title: "ICHR",
    subtitle: "ICHR Chair on Gandhi Studies",
    description: "Promotes research and academic programs on Gandhian philosophy, principles, and their application in contemporary society through dedicated study and scholarship.",
    externalLink: "https://christuniversity.in/center/C/ICHR",
    image: "https://christuniversity.in/uploads/centers/thumb/1227115096_2023-06-14_09-25-26.jpg",
    category: "Research",
  },
  {
    id: 30,
    slug: "sports",
    title: "Sports and Games",
    subtitle: "Centre for Sports Excellence",
    description: "Provides world-class sporting facilities, coaching, and competitive opportunities for students to excel in various sports and games at national and international levels.",
    externalLink: "https://christuniversity.in/center/C/sports",
    image: "https://christuniversity.in/uploads/centers/thumb/1539989876_2023-06-14_08-55-42.jpg",
    category: "Sports",
  },
];

// Helper function to get a centre by slug
export function getCentreBySlug(slug: string): Centre | undefined {
  return allCentres.find(c => c.slug.toLowerCase() === slug.toLowerCase());
}

// Helper function to get centres by category
export function getCentresByCategory(category: string): Centre[] {
  if (category === "All") return allCentres;
  return allCentres.filter(c => c.category === category);
}
